import type { PDFDocument, PDFPage, PDFFont, RGB } from 'pdf-lib'
import { formatCurrency, formatDeliveryExpectancy, sanitizeUnitForPdf } from './domain'
import type { AppSettings, LeadraMediaFile, LeadraUnit, LeadraUser } from './types'

type PdfRgb = typeof import('pdf-lib')['rgb']

interface BrandColors {
  ink: RGB
  olive: RGB
  copper: RGB
  sand: RGB
  paper: RGB
  line: RGB
  imageBackground: RGB
  heroSubtitle: RGB
}

export function buildPermissionSafePdfText(user: LeadraUser, unit: LeadraUnit, settings: AppSettings): string {
  const safeUnit = sanitizeUnitForPdf(user, unit)
  const installmentLine =
    safeUnit.paymentMethod === 'installment'
      ? `Installment: ${safeUnit.installmentType} at ${formatCurrency(safeUnit.installmentAmount)}`
      : 'Payment: Cash'
  const imageCount = safeUnit.media.filter((file) => file.type === 'image').length

  return [
    `${settings.companyName} Resale Unit PDF`,
    `Generated by: ${user.fullName}`,
    `Unit: ${safeUnit.unitCode}`,
    `Project: ${safeUnit.projectName}`,
    `Destination: ${safeUnit.destinationName}`,
    `Type: ${safeUnit.unitType}`,
    `Area: ${safeUnit.bua} BUA`,
    `Bedrooms/Bathrooms: ${safeUnit.bedrooms}/${safeUnit.bathrooms}`,
    `Pricing: ${formatCurrency(safeUnit.totalAmount)}`,
    `Commission: ${formatCurrency(safeUnit.commissionAmount)}`,
    installmentLine,
    `Delivery: ${formatDeliveryExpectancy(safeUnit)}`,
    imageCount > 0 ? `Images included: ${imageCount}` : 'No images attached',
    `Contact: ${settings.contactDetails}`,
    settings.footerText,
  ].join('\n')
}

export async function buildPermissionSafePdfBlob(user: LeadraUser, unit: LeadraUnit, settings: AppSettings): Promise<Blob> {
  const bytes = await buildBrandedPdfBytes(user, unit, settings)
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer
  return new Blob([buffer], { type: 'application/pdf' })
}

export async function downloadUnitPdf(user: LeadraUser, unit: LeadraUnit, settings: AppSettings): Promise<void> {
  const blob = await buildPermissionSafePdfBlob(user, unit, settings)
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${unit.unitCode}.pdf`
  link.rel = 'noopener'
  document.body.appendChild(link)
  link.click()
  link.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}

async function buildBrandedPdfBytes(user: LeadraUser, unit: LeadraUnit, settings: AppSettings): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib')
  const colors = createBrandColors(rgb)
  const safeUnit = sanitizeUnitForPdf(user, unit)
  const document = await PDFDocument.create()
  const regular = await document.embedFont(StandardFonts.Helvetica)
  const bold = await document.embedFont(StandardFonts.HelveticaBold)
  const page = document.addPage([595, 842])
  const { width, height } = page.getSize()
  const margin = 42

  page.drawRectangle({ x: 0, y: 0, width, height, color: colors.paper })
  page.drawRectangle({ x: margin, y: height - 150, width: width - margin * 2, height: 108, color: colors.ink })
  page.drawText(settings.companyName, { x: margin + 22, y: height - 82, size: 31, font: bold, color: colors.sand })
  page.drawText('Permission-safe resale unit brief', { x: margin + 24, y: height - 112, size: 11, font: regular, color: colors.heroSubtitle })
  page.drawText(safeUnit.unitCode, { x: width - margin - 132, y: height - 86, size: 18, font: bold, color: colors.sand })

  drawSectionTitle(page, bold, 'Unit overview', margin, height - 190, colors)
  drawKeyValue(page, regular, bold, 'Project', safeUnit.projectName, margin, height - 218, colors)
  drawKeyValue(page, regular, bold, 'Destination', safeUnit.destinationName, margin + 260, height - 218, colors)
  drawKeyValue(page, regular, bold, 'Type', `${safeUnit.unitType} / ${safeUnit.floor}`, margin, height - 246, colors)
  drawKeyValue(page, regular, bold, 'Area', `${safeUnit.bua} BUA`, margin + 260, height - 246, colors)
  drawKeyValue(page, regular, bold, 'Beds / Baths', `${safeUnit.bedrooms} / ${safeUnit.bathrooms}`, margin, height - 274, colors)
  drawKeyValue(page, regular, bold, 'Delivery', formatDeliveryExpectancy(safeUnit), margin + 260, height - 274, colors)

  drawSectionTitle(page, bold, 'Pricing and payment', margin, height - 330, colors)
  drawKeyValue(page, regular, bold, 'Total amount', formatCurrency(safeUnit.totalAmount), margin, height - 358, colors)
  drawKeyValue(page, regular, bold, 'Commission', `${formatCurrency(safeUnit.commissionAmount)} (${safeUnit.commissionPercentage}%)`, margin + 260, height - 358, colors)
  drawKeyValue(page, regular, bold, 'Payment method', safeUnit.paymentMethod, margin, height - 386, colors)
  drawKeyValue(page, regular, bold, 'Installment', formatCurrency(safeUnit.installmentAmount), margin + 260, height - 386, colors)

  drawSectionTitle(page, bold, 'Generated by', margin, height - 442, colors)
  drawKeyValue(page, regular, bold, 'Generated by', user.fullName, margin, height - 470, colors)

  drawSectionTitle(page, bold, 'Notes', margin, height - 526, colors)
  drawWrappedText(page, regular, safeUnit.salesNotes || 'No notes attached.', margin, height - 552, width - margin * 2, 10, colors.ink)

  page.drawLine({ start: { x: margin, y: 56 }, end: { x: width - margin, y: 56 }, thickness: 1, color: colors.line })
  page.drawText(`${settings.footerText} / ${settings.contactDetails}`, { x: margin, y: 38, size: 8, font: regular, color: colors.olive })

  await drawImages(document, safeUnit.media.filter((file) => file.type === 'image'), regular, bold, colors)

  return document.save()
}

async function drawImages(document: PDFDocument, images: LeadraMediaFile[], regular: PDFFont, bold: PDFFont, colors: BrandColors) {
  if (images.length === 0) {
    const page = document.addPage([595, 842])
    page.drawRectangle({ x: 0, y: 0, width: 595, height: 842, color: colors.paper })
    drawSectionTitle(page, bold, 'Unit images', 42, 780, colors)
    page.drawText('No images attached to this unit.', { x: 42, y: 750, size: 12, font: regular, color: colors.olive })
    return
  }

  let page = document.addPage([595, 842])
  page.drawRectangle({ x: 0, y: 0, width: 595, height: 842, color: colors.paper })
  drawSectionTitle(page, bold, 'Unit images', 42, 780, colors)
  let slot = 0

  for (const image of images) {
    const embedded = await embedImage(document, image)
    if (!embedded) continue

    if (slot >= 4) {
      page = document.addPage([595, 842])
      page.drawRectangle({ x: 0, y: 0, width: 595, height: 842, color: colors.paper })
      drawSectionTitle(page, bold, 'Unit images', 42, 780, colors)
      slot = 0
    }

    const col = slot % 2
    const row = Math.floor(slot / 2)
    const x = 42 + col * 258
    const y = 410 - row * 292
    const boxWidth = 238
    const boxHeight = 238
    const scale = Math.min(boxWidth / embedded.width, boxHeight / embedded.height)
    const imageWidth = embedded.width * scale
    const imageHeight = embedded.height * scale

    page.drawRectangle({ x, y, width: boxWidth, height: boxHeight, color: colors.imageBackground, borderColor: colors.line, borderWidth: 1 })
    page.drawImage(embedded, {
      x: x + (boxWidth - imageWidth) / 2,
      y: y + (boxHeight - imageHeight) / 2,
      width: imageWidth,
      height: imageHeight,
    })
    page.drawText(image.name.slice(0, 38), { x, y: y - 18, size: 8, font: regular, color: colors.olive })
    slot += 1
  }
}

async function embedImage(document: PDFDocument, image: LeadraMediaFile) {
  try {
    const bytes = await loadImageBytes(image.url)
    const lowerName = image.name.toLowerCase()
    if (image.url.startsWith('data:image/png') || lowerName.endsWith('.png')) return await document.embedPng(bytes)
    if (image.url.startsWith('data:image/jpeg') || image.url.startsWith('data:image/jpg') || lowerName.endsWith('.jpg') || lowerName.endsWith('.jpeg')) {
      return await document.embedJpg(bytes)
    }
    return null
  } catch {
    return null
  }
}

async function loadImageBytes(url: string): Promise<Uint8Array> {
  if (url.startsWith('data:')) {
    const [, payload = ''] = url.split(',')
    const isBase64 = url.slice(0, url.indexOf(',')).includes(';base64')
    const binary = isBase64 ? atob(payload) : decodeURIComponent(payload)
    return Uint8Array.from(binary, (char) => char.charCodeAt(0))
  }

  const response = await fetch(url)
  if (!response.ok) throw new Error('Image fetch failed')
  return new Uint8Array(await response.arrayBuffer())
}

function createBrandColors(rgb: PdfRgb): BrandColors {
  return {
    ink: rgb(0.08, 0.13, 0.11),
    olive: rgb(0.3, 0.42, 0.34),
    copper: rgb(0.71, 0.39, 0.24),
    sand: rgb(0.92, 0.84, 0.71),
    paper: rgb(0.98, 0.96, 0.9),
    line: rgb(0.83, 0.8, 0.72),
    imageBackground: rgb(0.99, 0.98, 0.94),
    heroSubtitle: rgb(0.92, 0.88, 0.78),
  }
}

function drawSectionTitle(page: PDFPage, font: PDFFont, title: string, x: number, y: number, colors: BrandColors) {
  page.drawText(title.toUpperCase(), { x, y, size: 10, font, color: colors.copper })
  page.drawLine({ start: { x, y: y - 8 }, end: { x: x + 510, y: y - 8 }, thickness: 1, color: colors.line })
}

function drawKeyValue(page: PDFPage, regular: PDFFont, bold: PDFFont, label: string, value: string, x: number, y: number, colors: BrandColors) {
  page.drawText(label, { x, y, size: 8, font: bold, color: colors.olive })
  page.drawText(value, { x, y: y - 14, size: 10, font: regular, color: colors.ink })
}

function drawWrappedText(page: PDFPage, font: PDFFont, text: string, x: number, y: number, maxWidth: number, size: number, color: RGB) {
  const words = text.split(/\s+/)
  const lines: string[] = []
  let current = ''

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) current = candidate
    else {
      if (current) lines.push(current)
      current = word
    }
  }

  if (current) lines.push(current)
  lines.slice(0, 7).forEach((line, index) => page.drawText(line, { x, y: y - index * 14, size, font, color }))
}
