import { describe, expect, it } from 'vitest'
import { demoUsers, initialAppState, seedUnits } from '../data/seed'
import { buildPermissionSafePdfBlob, buildPermissionSafePdfText } from './pdf'

describe('pdf generation', () => {
  it('builds a privacy-safe printable brief blob with branding and generator name only', async () => {
    const user = demoUsers[3]
    const unit = seedUnits[0]
    const settings = initialAppState.settings

    const text = buildPermissionSafePdfText(user, unit, settings)
    const blob = await buildPermissionSafePdfBlob(user, unit, settings)
    const html = await blob.text()

    expect(blob.type).toBe('text/html;charset=utf-8')
    expect(html).toContain('<!doctype html>')
    expect(html).toContain('dir="ltr"')
    expect(text).toContain(settings.companyName)
    expect(text).toContain(`Generated by: ${user.fullName}`)
    expect(text).toContain(settings.footerText)
    expect(text).toContain(settings.contactDetails)
    expect(text).not.toContain(user.phoneNumber)
    expect(text).not.toContain(user.role.replace('_', ' '))
    expect(text).not.toContain(unit.originalOwnerName)
    expect(text).not.toContain(unit.originalOwnerPhone)
  })

  it('renders readable unit images in printable html and sets rtl for Arabic', async () => {
    const user = demoUsers[0]
    const settings = initialAppState.settings
    const unit = {
      ...seedUnits[0],
      media: [
        {
          id: 'media-test-png',
          type: 'image' as const,
          name: 'tiny.png',
          sizeBytes: 68,
          url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg==',
        },
        {
          id: 'media-bad',
          type: 'image' as const,
          name: 'bad.png',
          sizeBytes: 4,
          url: 'data:image/png;base64,bad',
        },
      ],
    }

    const blob = await buildPermissionSafePdfBlob(user, unit, settings, 'ar')
    const html = await blob.text()

    expect(html).toContain('lang="ar-EG"')
    expect(html).toContain('dir="rtl"')
    expect(html).toContain('tiny.png')
    expect(html).toContain('data:image/png;base64')
  })
})
