import { PDFDocument } from 'pdf-lib'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { demoUsers, initialAppState, seedUnits } from '../data/seed'
import { buildPermissionSafePdfBlob, buildPermissionSafePdfText, generateUnitPdfFile, shareGeneratedPdfs } from './pdf'

describe('pdf generation', () => {
  afterEach(() => {
    vi.useRealTimers()
    vi.restoreAllMocks()
    vi.unstubAllGlobals()
  })

  it('builds a privacy-safe printable brief blob with branding and generator name only', async () => {
    const user = demoUsers[3]
    const unit = { ...seedUnits[0], media: [] }
    const settings = initialAppState.settings

    const text = buildPermissionSafePdfText(user, unit, settings)
    const blob = await buildPermissionSafePdfBlob(user, unit, settings)
    const header = await blob.slice(0, 5).text()

    expect(blob.type).toBe('application/pdf')
    expect(header).toBe('%PDF-')
    expect(text).toContain(settings.companyName)
    expect(text).toContain(`Generated by: ${user.fullName}`)
    expect(text.indexOf('Destination:')).toBeLessThan(text.indexOf('Developer:'))
    expect(text).toContain('Type: Apartment')
    expect(text).not.toContain('Payment method')
    expect(text).toContain(settings.footerText)
    expect(text).toContain(settings.contactDetails)
    expect(text).not.toContain(user.phoneNumber)
    expect(text).not.toContain(user.role.replace('_', ' '))
    expect(text).not.toContain(unit.originalOwnerName)
    expect(text).not.toContain(unit.originalOwnerPhone)
  })

  it('exports Penthouse wording and terrace area without floor or land fields', () => {
    const user = demoUsers[0]
    const unit = {
      ...seedUnits[0],
      unitType: 'Penthouse',
      floor: '',
      landArea: null,
      roofGardenArea: 48,
      gardenArea: null,
      terraceArea: 48,
    }
    const text = buildPermissionSafePdfText(user, unit, initialAppState.settings)

    expect(text).toContain('Type: Penthouse')
    expect(text).toContain('Terrace Area: 48')
    expect(text).not.toContain('Floor:')
    expect(text).not.toContain('Land Area:')
  })

  it('hides sales-only export fields when sales exports another user unit', async () => {
    const user = demoUsers[3]
    const unit = {
      ...seedUnits[0],
      createdBy: 'another-sales-user',
      salesNotes: 'Internal sales-only negotiation note',
      commissionAmount: 150000,
      commissionPercentage: 2,
    }
    const settings = initialAppState.settings

    const text = buildPermissionSafePdfText(user, unit, settings)
    const blob = await buildPermissionSafePdfBlob(user, { ...unit, media: [] }, settings)
    const header = await blob.slice(0, 5).text()

    expect(text).not.toContain('Internal sales-only negotiation note')
    expect(text).not.toContain('Commission')
    expect(text).not.toContain('150,000')
    expect(header).toBe('%PDF-')
  })

  it('builds a valid branded pdf with images while tolerating corrupt image data', async () => {
    const user = demoUsers[0]
    const settings = initialAppState.settings
    const unit = {
      ...seedUnits[0],
      media: [
        {
          id: 'media-test-png',
          type: 'image' as const,
          name: 'tiny.png',
          sizeBytes: 68,
          includeInPdf: true,
          url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg==',
        },
        {
          id: 'media-bad',
          type: 'image' as const,
          name: 'bad.png',
          sizeBytes: 4,
          includeInPdf: true,
          url: 'data:image/png;base64,bad',
        },
      ],
    }

    const blob = await buildPermissionSafePdfBlob(user, unit, settings, 'ar')
    const header = await blob.slice(0, 5).text()

    expect(blob.type).toBe('application/pdf')
    expect(header).toBe('%PDF-')
    expect(blob.size).toBeGreaterThan(1000)
  })

  it('aborts a hanging remote logo fetch and still generates a valid pdf', async () => {
    vi.useFakeTimers()
    const fetchMock = vi.fn((_url: string | URL | Request, init?: RequestInit) => new Promise<Response>((_resolve, reject) => {
      init?.signal?.addEventListener('abort', () => reject(new DOMException('Aborted', 'AbortError')))
    }))
    vi.stubGlobal('fetch', fetchMock)

    const promise = buildPermissionSafePdfBlob(
      demoUsers[0],
      { ...seedUnits[0], media: [] },
      { ...initialAppState.settings, logoPath: 'https://assets.leadra.test/logo.png' },
    )

    await vi.advanceTimersByTimeAsync(4000)
    const blob = await promise
    const header = await blob.slice(0, 5).text()

    expect(fetchMock).toHaveBeenCalledTimes(1)
    expect(fetchMock.mock.calls[0]?.[1]?.signal?.aborted).toBe(true)
    expect(blob.type).toBe('application/pdf')
    expect(header).toBe('%PDF-')
    expect(blob.size).toBeGreaterThan(1000)
  })

  it('falls back to browser-decoded PNG data when pdf-lib rejects image bytes', async () => {
    const user = demoUsers[0]
    const settings = initialAppState.settings
    const onePixelPng = Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg=='), (char) => char.charCodeAt(0))
    const originalImage = globalThis.Image
    const originalCreateElement = document.createElement.bind(document)
    const embedJpg = vi.spyOn(PDFDocument.prototype, 'embedJpg').mockRejectedValueOnce(new Error('unsupported jpeg'))
    const createElement = vi.spyOn(document, 'createElement').mockImplementation(((tagName: string, options?: ElementCreationOptions) => {
      if (tagName !== 'canvas') return originalCreateElement(tagName, options)
      return {
        width: 0,
        height: 0,
        getContext: () => ({ drawImage: vi.fn() }),
        toBlob: (callback: BlobCallback) => callback(new Blob([onePixelPng], { type: 'image/png' })),
      } as unknown as HTMLCanvasElement
    }) as typeof document.createElement)

    class TestImage {
      crossOrigin = ''
      naturalWidth = 1
      naturalHeight = 1
      width = 1
      height = 1
      onload: (() => void) | null = null
      onerror: (() => void) | null = null

      set src(_value: string) {
        window.setTimeout(() => this.onload?.(), 0)
      }
    }

    Object.defineProperty(globalThis, 'Image', { configurable: true, value: TestImage })

    try {
      const unit = {
        ...seedUnits[0],
        media: [{
          id: 'media-browser-decodes',
          type: 'image' as const,
          name: 'browser-decodes.jpg',
          sizeBytes: 16,
          includeInPdf: true,
          url: 'data:image/jpeg;base64,/9j/2w==',
        }],
      }

      const blob = await buildPermissionSafePdfBlob(user, unit, settings)
      const pdf = await PDFDocument.load(await blob.arrayBuffer())

      expect(embedJpg).toHaveBeenCalled()
      expect(createElement).toHaveBeenCalledWith('canvas')
      expect(pdf.getPageCount()).toBe(2)
      expect(blob.size).toBeGreaterThan(1000)
    } finally {
      if (originalImage) {
        Object.defineProperty(globalThis, 'Image', { configurable: true, value: originalImage })
      } else {
        Reflect.deleteProperty(globalThis, 'Image')
      }
    }
  })

  it('exports the PRD unit facts and omits payment-method wording', () => {
    const user = demoUsers[0]
    const unit = {
      ...seedUnits[0],
      finish: 'White Box',
      furnished: true,
      elevator: true,
      transferFees: 125_000,
      paymentSchedule: [
        { id: 'paid-1', unitId: seedUnits[0].id, paymentNumber: 1, dueMonth: '2026-06-01', amount: 123_456, paid: true, paidAt: null, paidBy: null, paidByName: null },
        { id: 'due-2', unitId: seedUnits[0].id, paymentNumber: 2, dueMonth: '2026-09-01', amount: 345_678, paid: false, paidAt: null, paidBy: null, paidByName: null },
      ],
    }

    const text = buildPermissionSafePdfText(user, unit, initialAppState.settings)

    expect(text).not.toContain('Unit Thumbnail')
    expect(text).not.toContain('Uploader Name')
    expect(text).not.toContain('living-room.jpg')
    expect(text).not.toContain('Sara Amin')
    expect(text).not.toContain('Unit Status:')
    expect(text.indexOf('Unit code: NC3BR')).toBeLessThan(text.indexOf('Destination: New Cairo'))
    expect(text.indexOf('Destination: New Cairo')).toBeLessThan(text.indexOf('Developer: Palm Hills'))
    expect(text).toContain('Project: New Cairo Estates')
    expect(text).toContain('Type: Apartment')
    expect(text).toContain('Floor / Position: 3rd')
    expect(text).toContain('BUA: 165 m2')
    expect(text).toContain('View: Landscape')
    expect(text).toContain('Bedrooms: 3')
    expect(text).toContain('Bathrooms: 2')
    expect(text).toContain('Elevator: Yes')
    expect(text).toContain('Furnished: Furnished')
    expect(text).toContain('Finishing Status *: White Box')
    expect(text).toContain('Total Amount: EGP\u00a05,000,000')
    expect(text).toContain('Down Payment: EGP\u00a01,123,456')
    expect(text).not.toContain('Paid Amount:')
    expect(text).toContain('Remaining Value: EGP\u00a0345,678')
    expect(text).toContain('Installments: Sep 2026: EGP\u00a0345,678')
    expect(text).not.toContain('Installment 1:')
    expect(text).not.toContain('Installment 2:')
    expect(text).toContain('Maintenance Paid: No')
    expect(text).toContain('Delivery Expectancy: March 2028')
    expect(text).toContain('Commission: EGP\u00a075,000 (1.5%)')
    expect(text).toContain('Transfer Fees: EGP\u00a0125,000')
    expect(text.indexOf('Installments:')).toBeLessThan(text.indexOf('Delivery Expectancy:'))
    expect(text.indexOf('Delivery Expectancy:')).toBeLessThan(text.indexOf('Commission:'))
    expect(text.indexOf('Commission:')).toBeLessThan(text.indexOf('Transfer Fees:'))
    expect(text).not.toContain('Payment method')
    expect(text).not.toContain('Payment Method')
  })

  it('keeps legacy PDF installment summary free of payment numbers and period labels when no due date exists', () => {
    const user = demoUsers[0]
    const unit = {
      ...seedUnits[0],
      paymentMethod: 'installment' as const,
      installmentType: 'semi_annual' as const,
      installmentAmount: 345_678,
      installmentYears: 1,
      installmentStartMonth: null,
      installmentEndMonth: null,
      paymentSchedule: [
        { id: 'legacy-next-1', unitId: seedUnits[0].id, paymentNumber: 1, dueMonth: null, amount: 345_678, paid: false, paidAt: null, paidBy: null, paidByName: null },
      ],
    }

    const text = buildPermissionSafePdfText(user, unit, initialAppState.settings)

    expect(text).toContain('Installments: EGP\u00a0345,678')
    expect(text).not.toContain('Installments: Next #1')
    expect(text).not.toContain('Installments: Half 1')
  })

  it('omits furnished and elevator facts unless selected and exports custom installment text', () => {
    const user = demoUsers[0]
    const unit = {
      ...seedUnits[0],
      furnished: false,
      elevator: false,
      installmentType: 'custom' as const,
      customInstallmentText: '10% every six months after handover',
      installmentAmount: 250_000,
    }

    const text = buildPermissionSafePdfText(user, unit, initialAppState.settings)

    expect(text).toContain('Custom Installment Text: 10% every six months after handover')
    expect(text).toContain('Installments: 10% every six months after handover')
    expect(text).not.toContain('Furnished:')
    expect(text).toContain('Elevator: No')
  })

  it('shows actual maintenance fields and falls back to the transfer-fee notice when no numeric fee is stored', () => {
    const user = demoUsers[0]
    const unit = {
      ...seedUnits[0],
      transferFees: null,
      maintenancePaid: true,
      maintenanceCost: 40_000,
      maintenanceDueDate: '2029-01-15',
    }

    const text = buildPermissionSafePdfText(user, unit, initialAppState.settings)

    expect(text).toContain('Maintenance Paid: Yes')
    expect(text).toContain('Maintenance Cost: EGP\u00a040,000')
    expect(text).toContain('Maintenance Due Date: January 15, 2029')
    expect(text).toContain('Transfer Fees: If Applicable')
  })

  it('embeds the uploaded company logo in generated pdf exports', async () => {
    const user = demoUsers[0]
    const unit = { ...seedUnits[0], media: [] }
    const logoPath = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg=='

    const withoutLogo = await buildPermissionSafePdfBlob(user, unit, { ...initialAppState.settings, logoPath: '' })
    const withLogo = await buildPermissionSafePdfBlob(user, unit, { ...initialAppState.settings, logoPath })
    const pdf = await PDFDocument.load(await withLogo.arrayBuffer())

    expect(pdf.getPageCount()).toBe(1)
    expect(withLogo.size).toBeGreaterThan(withoutLogo.size)
  })

  it('names generated pdf files with the unit code and export month day', async () => {
    const user = demoUsers[0]
    const unit = { ...seedUnits[0], media: [] }

    const first = await generateUnitPdfFile(user, unit, initialAppState.settings, 'en', new Date('2026-05-15T09:30:01Z'))
    const second = await generateUnitPdfFile(user, unit, initialAppState.settings, 'en', new Date('2026-05-15T09:31:02Z'))

    expect(first.fileName).toBe('NC3BR-May15.pdf')
    expect(second.fileName).toBe('NC3BR-May15.pdf')
  })

  it('includes visible and legacy unmarked images while excluding hidden images and videos', async () => {
    const user = demoUsers[0]
    const settings = initialAppState.settings
    const visibleImage = {
      id: 'media-visible',
      type: 'image' as const,
      name: 'visible.png',
      sizeBytes: 68,
      includeInPdf: true,
      url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg==',
    }
    const hiddenImage = { ...visibleImage, id: 'media-hidden', name: 'hidden.png', includeInPdf: false }
    const unmarkedImage = { ...visibleImage, id: 'media-unmarked', name: 'unmarked.png', includeInPdf: undefined }
    const video = { ...visibleImage, id: 'media-video', type: 'video' as never, name: 'walkthrough.mp4', includeInPdf: true }

    const withVisible = await buildPermissionSafePdfBlob(user, { ...seedUnits[0], media: [visibleImage] }, settings)
    const withExcludedOnly = await buildPermissionSafePdfBlob(user, { ...seedUnits[0], media: [hiddenImage, video] }, settings)
    const withLegacyUnmarked = await buildPermissionSafePdfBlob(user, { ...seedUnits[0], media: [unmarkedImage] }, settings)
    const visiblePdf = await PDFDocument.load(await withVisible.arrayBuffer())
    const excludedPdf = await PDFDocument.load(await withExcludedOnly.arrayBuffer())
    const legacyUnmarkedPdf = await PDFDocument.load(await withLegacyUnmarked.arrayBuffer())

    expect(visiblePdf.getPageCount()).toBe(2)
    expect(excludedPdf.getPageCount()).toBe(1)
    expect(legacyUnmarkedPdf.getPageCount()).toBe(2)
  })

  it('shares multiple generated pdf files when the browser supports them', async () => {
    const canShare = vi.fn(() => true)
    const share = vi.fn().mockResolvedValue(undefined)
    ensureTestNavigator()
    Object.defineProperty(navigator, 'canShare', { configurable: true, value: canShare })
    Object.defineProperty(navigator, 'share', { configurable: true, value: share })
    const pdfs = [
      { blob: new Blob(['one'], { type: 'application/pdf' }), fileName: 'leadra-one.pdf' },
      { blob: new Blob(['two'], { type: 'application/pdf' }), fileName: 'leadra-two.pdf' },
    ]

    await expect(shareGeneratedPdfs(pdfs)).resolves.toBe(true)

    expect(canShare).toHaveBeenCalledWith({ files: expect.arrayContaining([expect.any(File), expect.any(File)]) })
    expect(share).toHaveBeenCalledWith({
      files: expect.arrayContaining([expect.any(File), expect.any(File)]),
      title: '2 Leadra unit PDFs',
      text: 'Leadra unit PDFs',
    })
  })

  it('does not open native share for multiple pdf files when unsupported', async () => {
    const canShare = vi.fn(() => false)
    const share = vi.fn().mockResolvedValue(undefined)
    ensureTestNavigator()
    Object.defineProperty(navigator, 'canShare', { configurable: true, value: canShare })
    Object.defineProperty(navigator, 'share', { configurable: true, value: share })

    await expect(shareGeneratedPdfs([{ blob: new Blob(['one'], { type: 'application/pdf' }), fileName: 'leadra-one.pdf' }])).resolves.toBe(false)

    expect(share).not.toHaveBeenCalled()
  })
})

function ensureTestNavigator() {
  if (typeof navigator !== 'undefined') return
  Object.defineProperty(globalThis, 'navigator', {
    configurable: true,
    value: {},
  })
}
