import { PDFDocument } from 'pdf-lib'
import { describe, expect, it } from 'vitest'
import { demoUsers, initialAppState, seedUnits } from '../data/seed'
import { buildPermissionSafePdfBlob, buildPermissionSafePdfText } from './pdf'

describe('pdf generation', () => {
  it('builds a privacy-safe printable brief blob with branding and generator name only', async () => {
    const user = demoUsers[3]
    const unit = { ...seedUnits[0], media: [] }
    const settings = initialAppState.settings

    const text = buildPermissionSafePdfText(user, unit, settings)
    const blob = await buildPermissionSafePdfBlob(user, unit, settings)
    const header = await blob.slice(0, 5).text()

    expect(blob.type).toBe('application/pdf')
    expect(header).toBe('%PDF-')
    expect(text).toContain(settings.companyName)
    expect(text).toContain(`Generated by: ${user.fullName}`)
    expect(text.indexOf('Destination:')).toBeLessThan(text.indexOf('Developer:'))
    expect(text).toContain('Type: Apartment')
    expect(text).not.toContain('Payment method')
    expect(text).toContain(settings.footerText)
    expect(text).toContain(settings.contactDetails)
    expect(text).not.toContain(user.phoneNumber)
    expect(text).not.toContain(user.role.replace('_', ' '))
    expect(text).not.toContain(unit.originalOwnerName)
    expect(text).not.toContain(unit.originalOwnerPhone)
  })

  it('exports Penthouse wording and terrace area without floor or land fields', () => {
    const user = demoUsers[0]
    const unit = {
      ...seedUnits[0],
      unitType: 'Penthouse',
      floor: '',
      landArea: null,
      roofGardenArea: 48,
      gardenArea: null,
      terraceArea: 48,
    }
    const text = buildPermissionSafePdfText(user, unit, initialAppState.settings)

    expect(text).toContain('Type: Penthouse')
    expect(text).toContain('Terrace Area: 48')
    expect(text).not.toContain('Floor:')
    expect(text).not.toContain('Land Area:')
  })

  it('hides sales-only export fields when sales exports another user unit', async () => {
    const user = demoUsers[3]
    const unit = {
      ...seedUnits[0],
      createdBy: 'another-sales-user',
      salesNotes: 'Internal sales-only negotiation note',
      commissionAmount: 150000,
      commissionPercentage: 2,
    }
    const settings = initialAppState.settings

    const text = buildPermissionSafePdfText(user, unit, settings)
    const blob = await buildPermissionSafePdfBlob(user, { ...unit, media: [] }, settings)
    const header = await blob.slice(0, 5).text()

    expect(text).not.toContain('Internal sales-only negotiation note')
    expect(text).not.toContain('Commission')
    expect(text).not.toContain('150,000')
    expect(header).toBe('%PDF-')
  })

  it('builds a valid branded pdf with images while tolerating corrupt image data', async () => {
    const user = demoUsers[0]
    const settings = initialAppState.settings
    const unit = {
      ...seedUnits[0],
      media: [
        {
          id: 'media-test-png',
          type: 'image' as const,
          name: 'tiny.png',
          sizeBytes: 68,
          url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg==',
        },
        {
          id: 'media-bad',
          type: 'image' as const,
          name: 'bad.png',
          sizeBytes: 4,
          url: 'data:image/png;base64,bad',
        },
      ],
    }

    const blob = await buildPermissionSafePdfBlob(user, unit, settings, 'ar')
    const header = await blob.slice(0, 5).text()

    expect(blob.type).toBe('application/pdf')
    expect(header).toBe('%PDF-')
    expect(blob.size).toBeGreaterThan(1000)
  })

  it('excludes images marked hidden from the generated pdf', async () => {
    const user = demoUsers[0]
    const settings = initialAppState.settings
    const visibleImage = {
      id: 'media-visible',
      type: 'image' as const,
      name: 'visible.png',
      sizeBytes: 68,
      includeInPdf: true,
      url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lZrD9wAAAABJRU5ErkJggg==',
    }
    const hiddenImage = { ...visibleImage, id: 'media-hidden', name: 'hidden.png', includeInPdf: false }

    const withVisible = await buildPermissionSafePdfBlob(user, { ...seedUnits[0], media: [visibleImage] }, settings)
    const withHiddenOnly = await buildPermissionSafePdfBlob(user, { ...seedUnits[0], media: [hiddenImage] }, settings)
    const visiblePdf = await PDFDocument.load(await withVisible.arrayBuffer())
    const hiddenPdf = await PDFDocument.load(await withHiddenOnly.arrayBuffer())

    expect(visiblePdf.getPageCount()).toBe(2)
    expect(hiddenPdf.getPageCount()).toBe(1)
  })
})
