import { formatCurrency, formatDeliveryExpectancy, sanitizeUnitForPdf } from './domain'
import type { LeadraUnit, LeadraUser } from './types'

export function buildPermissionSafePdfText(user: LeadraUser, unit: LeadraUnit): string {
  const safeUnit = sanitizeUnitForPdf(user, unit)
  const ownerLine = safeUnit.originalOwnerName
    ? `Owner: ${safeUnit.originalOwnerName} / ${safeUnit.originalOwnerPhone}`
    : 'Owner: Hidden by Leadra permissions'
  const installmentLine =
    safeUnit.paymentMethod === 'installment'
      ? `Installment: ${safeUnit.installmentType} at ${formatCurrency(safeUnit.installmentAmount)}`
      : 'Payment: Cash'

  return [
    'Leadra Resale Unit PDF',
    `Generated by: ${user.fullName}`,
    `Generator phone: ${user.phoneNumber}`,
    `Generator role: ${user.role.replace('_', ' ')}`,
    `Unit: ${safeUnit.unitCode}`,
    `Project: ${safeUnit.projectName}`,
    `Destination: ${safeUnit.destinationName}`,
    `Type: ${safeUnit.unitType}`,
    `Area: ${safeUnit.bua} BUA`,
    `Bedrooms/Bathrooms: ${safeUnit.bedrooms}/${safeUnit.bathrooms}`,
    `Pricing: ${formatCurrency(safeUnit.totalAmount)}`,
    `Commission: ${formatCurrency(safeUnit.commissionAmount)}`,
    installmentLine,
    `Delivery: ${formatDeliveryExpectancy(safeUnit)}`,
    ownerLine,
    `Images included: ${safeUnit.media.filter((file) => file.type === 'image').length}`,
  ].join('\n')
}

export function buildPermissionSafePdfBlob(user: LeadraUser, unit: LeadraUnit): Blob {
  const bytes = buildSimplePdfBytes(buildPermissionSafePdfText(user, unit))
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer
  return new Blob([buffer], { type: 'application/pdf' })
}

export function downloadTextPdfFallback(user: LeadraUser, unit: LeadraUnit): void {
  const blob = buildPermissionSafePdfBlob(user, unit)
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${unit.unitCode}.pdf`
  link.rel = 'noopener'
  document.body.appendChild(link)
  link.click()
  link.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function buildSimplePdfBytes(text: string): Uint8Array {
  const lines = text.split('\n')
  const content = [
    'BT',
    '/F1 18 Tf',
    '50 790 Td',
    '(Leadra Resale Unit PDF) Tj',
    '/F1 11 Tf',
    '0 -24 Td',
    ...lines.slice(1).flatMap((line) => [`(${escapePdfText(line)}) Tj`, '0 -16 Td']),
    'ET',
  ].join('\n')
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${byteLength(content)} >>\nstream\n${content}\nendstream`,
  ]
  const chunks = ['%PDF-1.4\n%\xE2\xE3\xCF\xD3\n']
  const offsets = [0]

  for (const [index, object] of objects.entries()) {
    offsets.push(byteLength(chunks.join('')))
    chunks.push(`${index + 1} 0 obj\n${object}\nendobj\n`)
  }

  const xrefOffset = byteLength(chunks.join(''))
  chunks.push(`xref\n0 ${objects.length + 1}\n`)
  chunks.push('0000000000 65535 f \n')
  offsets.slice(1).forEach((offset) => {
    chunks.push(`${String(offset).padStart(10, '0')} 00000 n \n`)
  })
  chunks.push(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`)

  return new TextEncoder().encode(chunks.join(''))
}

function escapePdfText(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function byteLength(text: string): number {
  return new TextEncoder().encode(text).length
}
