import type { SupabaseClient, User } from '@supabase/supabase-js'
import { LeadraRepository } from './repository'
import type {
  AnalyticsEvent,
  AnalyticsTarget,
  AppDataState,
  AppSettings,
  AuditLogItem,
  LeadraUser,
  LookupValue,
  NotificationItem,
  UserRole,
} from './types'

interface RemoteState {
  state: AppDataState
  lookupValues: LookupValue[]
}

export async function loadSupabaseProfile(client: SupabaseClient, authUser: User): Promise<LeadraUser> {
  const { data, error } = await client.from('profiles').select('*').eq('id', authUser.id).single()
  if (error) throw new Error(`Profile load failed: ${error.message}`)
  if (!data) throw new Error('No profile exists for this Supabase user.')

  return toLeadraUser(data)
}

export async function markSupabaseLogin(client: SupabaseClient): Promise<void> {
  const { error } = await client.rpc('mark_own_login')
  if (error) console.warn('Supabase login timestamp was not updated:', error.message)
}

export async function loadSupabaseAppState(client: SupabaseClient): Promise<RemoteState> {
  const repository = new LeadraRepository(client)
  const [users, units, lookupValues, settings, notifications, auditLogs, analyticsEvents, analyticsTargets] = await Promise.all([
    loadProfiles(client),
    repository.listUnits(),
    loadLookupValues(client),
    loadSettings(client),
    loadNotifications(client),
    loadAuditLogs(client),
    loadAnalyticsEvents(client),
    loadAnalyticsTargets(client),
  ])

  return {
    lookupValues,
    state: {
      users,
      units,
      notifications,
      auditLogs,
      analyticsEvents,
      analyticsTargets,
      settings,
    },
  }
}

async function loadProfiles(client: SupabaseClient): Promise<LeadraUser[]> {
  const { data, error } = await client.from('profiles').select('*').order('role').order('full_name')
  if (error) throw new Error(`Users load failed: ${error.message}`)
  return (data ?? []).map(toLeadraUser)
}

async function loadLookupValues(client: SupabaseClient): Promise<LookupValue[]> {
  const { data, error } = await client
    .from('lookup_values')
    .select('id, kind, label, archived')
    .eq('archived', false)
    .order('kind')
    .order('label')
  if (error) throw new Error(`Lookup values load failed: ${error.message}`)
  return (data ?? []).map((row) => ({
    id: String(row.id),
    kind: row.kind,
    label: row.label,
    archived: row.archived,
  }))
}

async function loadSettings(client: SupabaseClient): Promise<AppSettings> {
  const { data, error } = await client.from('app_settings').select('*').eq('id', true).single()
  if (error) throw new Error(`Settings load failed: ${error.message}`)
  return {
    companyName: data.company_name ?? 'Leadra',
    commissionPercentage: Number(data.commission_percentage ?? 1.5),
    footerText: data.footer_text ?? 'Generated by Leadra resale system',
    contactDetails: data.contact_details ?? '',
    mediaLimitMb: Number(data.media_limit_mb ?? 40),
    paymentMethods: ['cash', 'installment'],
  }
}

async function loadNotifications(client: SupabaseClient): Promise<NotificationItem[]> {
  const { data, error } = await client
    .from('notifications')
    .select('id, user_id, audience_role, title, body, read_at, created_at')
    .order('created_at', { ascending: false })
  if (error) throw new Error(`Notifications load failed: ${error.message}`)
  return (data ?? []).map((row) => ({
    id: String(row.id),
    title: row.title,
    body: row.body,
    audienceRole: row.audience_role ?? undefined,
    userId: row.user_id ?? undefined,
    createdAt: row.created_at,
    read: Boolean(row.read_at),
  }))
}

async function loadAuditLogs(client: SupabaseClient): Promise<AuditLogItem[]> {
  const { data, error } = await client
    .from('audit_logs')
    .select('id, actor_role, action_type, previous_value, new_value, ip_address, created_at, actor:profiles!audit_logs_actor_id_fkey(full_name), unit:units!audit_logs_related_unit_id_fkey(unit_code)')
    .order('created_at', { ascending: false })
  if (error) throw new Error(`Audit logs load failed: ${error.message}`)
  return (data ?? []).map((row) => ({
    id: String(row.id),
    actorName: joinedLabel(row.actor, 'full_name') ?? 'Leadra user',
    actorRole: row.actor_role,
    actionType: row.action_type,
    relatedUnitCode: joinedLabel(row.unit, 'unit_code') ?? undefined,
    previousValue: row.previous_value == null ? null : JSON.stringify(row.previous_value),
    newValue: row.new_value == null ? null : JSON.stringify(row.new_value),
    ipAddress: row.ip_address,
    createdAt: row.created_at,
  }))
}

async function loadAnalyticsEvents(client: SupabaseClient): Promise<AnalyticsEvent[]> {
  const { data, error } = await client.from('analytics_events').select('*').order('created_at', { ascending: false })
  if (error) throw new Error(`Analytics events load failed: ${error.message}`)
  return (data ?? []).map((row) => ({
    id: String(row.id),
    eventType: row.event_type,
    actorId: row.actor_id,
    actorRole: row.actor_role,
    teamId: row.team_id,
    branchId: row.branch_id,
    unitId: row.unit_id,
    projectId: row.project_id,
    developerId: row.developer_id,
    destinationId: row.destination_id,
    unitStatusBefore: row.unit_status_before,
    unitStatusAfter: row.unit_status_after,
    amountValue: row.amount_value == null ? null : Number(row.amount_value),
    commissionValue: row.commission_value == null ? null : Number(row.commission_value),
    metadata: row.metadata ?? {},
    createdAt: row.created_at,
  }))
}

async function loadAnalyticsTargets(client: SupabaseClient): Promise<AnalyticsTarget[]> {
  const { data, error } = await client.from('analytics_targets').select('*').order('starts_at', { ascending: false })
  if (error) throw new Error(`Analytics targets load failed: ${error.message}`)
  return (data ?? []).map((row) => ({
    id: String(row.id),
    scopeType: row.scope_type,
    scopeId: row.scope_id,
    period: row.period,
    targetUnitsCreated: Number(row.target_units_created ?? 0),
    targetUnitsSold: Number(row.target_units_sold ?? 0),
    targetSoldValue: Number(row.target_sold_value ?? 0),
    targetCommission: Number(row.target_commission ?? 0),
    targetActivityEvents: Number(row.target_activity_events ?? 0),
    startsAt: row.starts_at,
    endsAt: row.ends_at,
    createdBy: row.created_by,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }))
}

function toLeadraUser(row: Record<string, unknown>): LeadraUser {
  return {
    id: String(row.id),
    fullName: String(row.full_name ?? 'Leadra user'),
    email: String(row.email ?? ''),
    role: String(row.role ?? 'sales') as UserRole,
    jobTitle: String(row.job_title ?? 'Team member'),
    phoneNumber: String(row.phone_number ?? ''),
    teamId: String(row.team_id ?? ''),
    branchId: String(row.branch_id ?? ''),
    status: row.status === 'inactive' ? 'inactive' : 'active',
    createdAt: typeof row.created_at === 'string' ? row.created_at : undefined,
    lastLoginAt: typeof row.last_login_at === 'string' ? row.last_login_at : null,
  }
}

function joinedLabel(value: unknown, key: string): string | null {
  if (Array.isArray(value)) return joinedLabel(value[0], key)
  if (value && typeof value === 'object' && key in value) return String((value as Record<string, unknown>)[key])
  return null
}
