import type { SupabaseClient, User } from '@supabase/supabase-js'
import { LeadraRepository } from './repository'
import { compareText } from './i18n'
import type {
  AnalyticsChartPoint,
  AnalyticsDashboard,
  AnalyticsEvent,
  AnalyticsFilters,
  AnalyticsInventoryHealth,
  AnalyticsSalesPerformance,
  AnalyticsTarget,
  AnalyticsTargetProgress,
  AnalyticsTimelinePoint,
  AppDataState,
  AppSettings,
  AuditLogItem,
  BranchDirectoryItem,
  LeadraUser,
  LookupValue,
  MessageParams,
  NotificationItem,
  TeamDirectoryItem,
  ThemePreference,
  UserRole,
} from './types'

const remoteLoadLimits = {
  users: 250,
  notifications: 250,
  auditLogs: 500,
  analyticsEvents: 1000,
  analyticsTargets: 200,
} as const

interface RemoteState {
  state: AppDataState
  lookupValues: LookupValue[]
}

export function createSupabaseShellState(profile: LeadraUser): AppDataState {
  return {
    users: [profile],
    units: [],
    branches: [],
    teams: [],
    notifications: [],
    auditLogs: [],
    analyticsEvents: [],
    analyticsTargets: [],
    settings: {
      companyName: 'Leadra',
      commissionPercentage: 1.5,
      footerText: 'Generated by Leadra resale system',
      contactDetails: '',
      logoPath: '',
      pdfLayout: 'classic',
      mediaLimitMb: 40,
      paymentMethods: ['cash', 'installment'],
    },
  }
}

interface SafeAuditLogRow {
  id: string
  actor_name: string | null
  actor_role: UserRole
  action_type: string
  message_key: string | null
  message_params: MessageParams | null
  related_unit_code: string | null
  previous_value: unknown
  new_value: unknown
  ip_address: string | null
  created_at: string
}

export async function loadSupabaseProfile(client: SupabaseClient, authUser: User): Promise<LeadraUser> {
  const { data, error } = await client.from('profiles').select('*').eq('id', authUser.id).single()
  if (error) throw new Error(`Profile load failed: ${error.message}`)
  if (!data) throw new Error('No profile exists for this Supabase user.')

  return toLeadraUser(data)
}

export async function markSupabaseLogin(client: SupabaseClient): Promise<void> {
  const { error } = await client.rpc('mark_own_login')
  if (error) console.warn('Supabase login timestamp was not updated:', error.message)
}

export async function setSupabaseThemePreference(client: SupabaseClient, themePreference: ThemePreference): Promise<LeadraUser> {
  const { data, error } = await client.rpc('set_own_theme_preference', { theme: themePreference })
  if (error) throw new Error(`Theme update failed: ${error.message}`)
  const profile = Array.isArray(data) ? data[0] : data
  if (!profile) throw new Error('Theme update failed.')
  return toLeadraUser(profile as Record<string, unknown>)
}

export async function loadSupabaseAppState(client: SupabaseClient): Promise<RemoteState> {
  const repository = new LeadraRepository(client)
  await repository.reconcileDueUnitPayments()
  const [users, units, branches, teams, lookupValues, settings, notifications, auditLogs, analyticsEvents, analyticsTargets] = await Promise.all([
    loadProfiles(client),
    repository.listUnits(),
    loadBranches(client),
    loadTeams(client),
    loadLookupValues(client),
    loadSettings(client),
    loadNotifications(client),
    loadAuditLogs(client),
    loadAnalyticsEvents(client),
    loadAnalyticsTargets(client),
  ])

  return {
    lookupValues,
    state: {
      users,
      units,
      branches,
      teams,
      notifications,
      auditLogs,
      analyticsEvents,
      analyticsTargets,
      settings,
    },
  }
}

export async function loadSupabaseAnalyticsDashboard(client: SupabaseClient, filters: AnalyticsFilters): Promise<AnalyticsDashboard> {
  const { data, error } = await client.rpc('analytics_dashboard', { filters })
  if (error) throw new Error(`Analytics load failed: ${error.message}`)
  return toAnalyticsDashboard(data as Record<string, unknown>)
}

async function loadProfiles(client: SupabaseClient): Promise<LeadraUser[]> {
  const { data, error } = await client.from('profiles').select('*').order('role').order('full_name').limit(remoteLoadLimits.users)
  if (error) throw new Error(`Users load failed: ${error.message}`)
  return (data ?? []).map(toLeadraUser)
}

async function loadLookupValues(client: SupabaseClient): Promise<LookupValue[]> {
  const { data, error } = await client
    .from('lookup_values')
    .select('id, kind, label, thumbnail_path, archived')
    .eq('archived', false)
    .order('kind')
  if (error) throw new Error(`Lookup values load failed: ${error.message}`)
  return (data ?? [])
    .map((row) => ({
      id: String(row.id),
      kind: row.kind,
      label: row.label,
      thumbnailPath: row.thumbnail_path,
      archived: row.archived,
    }))
    .sort((first, second) => compareText('en', first.label, second.label))
}

async function loadSettings(client: SupabaseClient): Promise<AppSettings> {
  const { data, error } = await client.from('app_settings').select('*').eq('id', true).single()
  if (error) throw new Error(`Settings load failed: ${error.message}`)
  return {
    companyName: data.company_name ?? 'Leadra',
    commissionPercentage: Number(data.commission_percentage ?? 1.5),
    footerText: data.footer_text ?? 'Generated by Leadra resale system',
    contactDetails: data.contact_details ?? '',
    logoPath: data.logo_path ?? '',
    pdfLayout: data.pdf_layout === 'compact' ? 'compact' : 'classic',
    mediaLimitMb: Number(data.media_limit_mb ?? 40),
    paymentMethods: ['cash', 'installment'],
  }
}

async function loadNotifications(client: SupabaseClient): Promise<NotificationItem[]> {
  const { data, error } = await client
    .from('notifications')
    .select('id, user_id, audience_role, title, body, message_key, message_params, read_at, created_at')
    .order('created_at', { ascending: false })
    .limit(remoteLoadLimits.notifications)
  if (error) throw new Error(`Notifications load failed: ${error.message}`)
  return ((data ?? []) as Record<string, unknown>[]).map((row) => ({
    id: String(row.id),
    title: String(row.title ?? ''),
    body: String(row.body ?? ''),
    messageKey: typeof row.message_key === 'string' ? row.message_key : null,
    messageParams: row.message_params && typeof row.message_params === 'object' ? row.message_params : null,
    audienceRole: typeof row.audience_role === 'string' ? row.audience_role : undefined,
    userId: typeof row.user_id === 'string' ? row.user_id : undefined,
    createdAt: String(row.created_at ?? ''),
    read: Boolean(row.read_at),
  }) as NotificationItem)
}

async function loadAuditLogs(client: SupabaseClient): Promise<AuditLogItem[]> {
  const { data, error } = await client.rpc('list_audit_logs_safe', { limit_count: remoteLoadLimits.auditLogs })
  if (error) throw new Error(`Audit logs load failed: ${error.message}`)
  return ((data ?? []) as SafeAuditLogRow[]).map((row) => ({
    id: String(row.id),
    actorName: row.actor_name ?? 'Leadra user',
    actorRole: row.actor_role,
    actionType: row.action_type,
    messageKey: row.message_key ?? null,
    messageParams: row.message_params ?? null,
    relatedUnitCode: row.related_unit_code ?? undefined,
    previousValue: row.previous_value == null ? null : JSON.stringify(row.previous_value),
    newValue: row.new_value == null ? null : JSON.stringify(row.new_value),
    ipAddress: row.ip_address,
    createdAt: row.created_at,
  }))
}

async function loadAnalyticsEvents(client: SupabaseClient): Promise<AnalyticsEvent[]> {
  const { data, error } = await client.from('analytics_events').select('*').order('created_at', { ascending: false }).limit(remoteLoadLimits.analyticsEvents)
  if (error) throw new Error(`Analytics events load failed: ${error.message}`)
  return ((data ?? []) as Record<string, unknown>[]).map((row) => ({
    id: String(row.id),
    eventType: row.event_type,
    actorId: row.actor_id,
    actorRole: row.actor_role,
    teamId: row.team_id,
    branchId: row.branch_id,
    unitId: row.unit_id,
    projectId: row.project_id,
    developerId: row.developer_id,
    destinationId: row.destination_id,
    unitStatusBefore: row.unit_status_before,
    unitStatusAfter: row.unit_status_after,
    amountValue: row.amount_value == null ? null : Number(row.amount_value),
    commissionValue: row.commission_value == null ? null : Number(row.commission_value),
    metadata: row.metadata ?? {},
    createdAt: row.created_at,
  }) as AnalyticsEvent)
}

async function loadAnalyticsTargets(client: SupabaseClient): Promise<AnalyticsTarget[]> {
  const { data, error } = await client.from('analytics_targets').select('*').order('starts_at', { ascending: false }).limit(remoteLoadLimits.analyticsTargets)
  if (error) throw new Error(`Analytics targets load failed: ${error.message}`)
  return ((data ?? []) as Record<string, unknown>[]).map((row) => ({
    id: String(row.id),
    scopeType: row.scope_type,
    scopeId: row.scope_id,
    period: row.period,
    targetUnitsCreated: Number(row.target_units_created ?? 0),
    targetUnitsSold: Number(row.target_units_sold ?? 0),
    targetSoldValue: Number(row.target_sold_value ?? 0),
    targetCommission: Number(row.target_commission ?? 0),
    targetActivityEvents: Number(row.target_activity_events ?? 0),
    startsAt: row.starts_at,
    endsAt: row.ends_at,
    createdBy: row.created_by,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }) as AnalyticsTarget)
}

function toLeadraUser(row: Record<string, unknown>): LeadraUser {
  return {
    id: String(row.id),
    fullName: String(row.full_name ?? 'Leadra user'),
    email: String(row.email ?? ''),
    role: String(row.role ?? 'sales') as UserRole,
    jobTitle: String(row.job_title ?? 'Team member'),
    phoneNumber: String(row.phone_number ?? ''),
    teamId: String(row.team_id ?? ''),
    branchId: String(row.branch_id ?? ''),
    status: row.status === 'inactive' ? 'inactive' : 'active',
    themePreference: row.theme_preference === 'dark' ? 'dark' : 'light',
    createdAt: typeof row.created_at === 'string' ? row.created_at : undefined,
    lastLoginAt: typeof row.last_login_at === 'string' ? row.last_login_at : null,
    deletedAt: typeof row.deleted_at === 'string' ? row.deleted_at : null,
  }
}

async function loadBranches(client: SupabaseClient): Promise<BranchDirectoryItem[]> {
  const { data, error } = await client
    .from('branches')
    .select('id, name, archived')
    .eq('archived', false)
    .order('name')
  if (error) throw new Error(`Branches load failed: ${error.message}`)
  return ((data ?? []) as Record<string, unknown>[]).map((row) => ({
    id: String(row.id),
    name: String(row.name ?? row.id),
    archived: Boolean(row.archived),
  }))
}

async function loadTeams(client: SupabaseClient): Promise<TeamDirectoryItem[]> {
  const { data, error } = await client
    .from('teams')
    .select('id, name, branch_id, archived')
    .eq('archived', false)
    .order('name')
  if (error) throw new Error(`Teams load failed: ${error.message}`)
  return ((data ?? []) as Record<string, unknown>[]).map((row) => ({
    id: String(row.id),
    name: String(row.name ?? row.id),
    branchId: typeof row.branch_id === 'string' ? row.branch_id : null,
    archived: Boolean(row.archived),
  }))
}

function toAnalyticsDashboard(row: Record<string, unknown>): AnalyticsDashboard {
  const overview = objectValue(row.overview)
  return {
    scopeLabel: String(row.scopeLabel ?? row.scope_label ?? 'Company-wide'),
    overview: {
      totalActiveUnits: numberValue(overview.totalActiveUnits ?? overview.total_active_units),
      availableUnits: numberValue(overview.availableUnits ?? overview.available_units),
      holdUnits: numberValue(overview.holdUnits ?? overview.hold_units),
      soldUnits: numberValue(overview.soldUnits ?? overview.sold_units),
      soldValue: numberValue(overview.soldValue ?? overview.sold_value),
      projectedCommission: numberValue(overview.projectedCommission ?? overview.projected_commission),
      activeUsers: numberValue(overview.activeUsers ?? overview.active_users),
      duplicateAttempts: numberValue(overview.duplicateAttempts ?? overview.duplicate_attempts),
      pdfExports: numberValue(overview.pdfExports ?? overview.pdf_exports),
      inactiveUsers: numberValue(overview.inactiveUsers ?? overview.inactive_users),
      archivedUnits: numberValue(overview.archivedUnits ?? overview.archived_units),
      staleUnits: numberValue(overview.staleUnits ?? overview.stale_units),
    },
    salesPerformance: arrayValue(row.salesPerformance ?? row.sales_performance).map(toSalesPerformance),
    inventoryHealth: arrayValue(row.inventoryHealth ?? row.inventory_health).map(toInventoryHealth),
    activityTimeline: arrayValue(row.activityTimeline ?? row.activity_timeline).map(toTimelinePoint),
    soldValueTrend: arrayValue(row.soldValueTrend ?? row.sold_value_trend).map(toChartPoint),
    pdfExportTrend: arrayValue(row.pdfExportTrend ?? row.pdf_export_trend).map(toChartPoint),
    targetProgress: arrayValue(row.targetProgress ?? row.target_progress).map(toTargetProgress),
    filterOptions: {
      teams: arrayValue(objectValue(row.filterOptions ?? row.filter_options).teams).map(toOption),
      users: arrayValue(objectValue(row.filterOptions ?? row.filter_options).users).map(toOption),
      projects: arrayValue(objectValue(row.filterOptions ?? row.filter_options).projects).map(toOption),
      developers: arrayValue(objectValue(row.filterOptions ?? row.filter_options).developers).map(toOption),
      destinations: arrayValue(objectValue(row.filterOptions ?? row.filter_options).destinations).map(toOption),
    },
  }
}

function toSalesPerformance(row: Record<string, unknown>): AnalyticsSalesPerformance {
  return {
    userId: String(row.userId ?? row.user_id ?? ''),
    userName: String(row.userName ?? row.user_name ?? 'Leadra user'),
    role: 'sales',
    teamId: String(row.teamId ?? row.team_id ?? ''),
    unitsCreated: numberValue(row.unitsCreated ?? row.units_created),
    unitsSold: numberValue(row.unitsSold ?? row.units_sold),
    soldValue: numberValue(row.soldValue ?? row.sold_value),
    commissionContribution: numberValue(row.commissionContribution ?? row.commission_contribution),
    activityCount: numberValue(row.activityCount ?? row.activity_count),
    lastActivityAt: typeof (row.lastActivityAt ?? row.last_activity_at) === 'string' ? String(row.lastActivityAt ?? row.last_activity_at) : null,
  }
}

function toInventoryHealth(row: Record<string, unknown>): AnalyticsInventoryHealth {
  return {
    projectId: String(row.projectId ?? row.project_id ?? ''),
    projectName: String(row.projectName ?? row.project_name ?? 'Unknown project'),
    developerName: String(row.developerName ?? row.developer_name ?? 'Unknown developer'),
    destinationName: String(row.destinationName ?? row.destination_name ?? 'Unknown destination'),
    totalUnits: numberValue(row.totalUnits ?? row.total_units),
    availableUnits: numberValue(row.availableUnits ?? row.available_units),
    holdUnits: numberValue(row.holdUnits ?? row.hold_units),
    soldUnits: numberValue(row.soldUnits ?? row.sold_units),
    holdRatio: numberValue(row.holdRatio ?? row.hold_ratio),
    averagePrice: numberValue(row.averagePrice ?? row.average_price),
    mediaCompleteness: numberValue(row.mediaCompleteness ?? row.media_completeness),
    staleUnits: numberValue(row.staleUnits ?? row.stale_units),
  }
}

function toTimelinePoint(row: Record<string, unknown>): AnalyticsTimelinePoint {
  return {
    date: String(row.date ?? row.activity_date ?? ''),
    unitsCreated: numberValue(row.unitsCreated ?? row.units_created),
    statusChanges: numberValue(row.statusChanges ?? row.status_changes),
    soldValue: numberValue(row.soldValue ?? row.sold_value),
    pdfExports: numberValue(row.pdfExports ?? row.pdf_exports),
    activityCount: numberValue(row.activityCount ?? row.activity_count),
  }
}

function toChartPoint(row: Record<string, unknown>): AnalyticsChartPoint {
  return {
    date: String(row.date ?? ''),
    label: String(row.label ?? row.date ?? ''),
    value: numberValue(row.value),
  }
}

function toTargetProgress(row: Record<string, unknown>): AnalyticsTargetProgress {
  return {
    targetId: String(row.targetId ?? row.target_id ?? ''),
    label: String(row.label ?? 'Target'),
    unitsCreatedProgress: numberValue(row.unitsCreatedProgress ?? row.units_created_progress),
    unitsSoldProgress: numberValue(row.unitsSoldProgress ?? row.units_sold_progress),
    soldValueProgress: numberValue(row.soldValueProgress ?? row.sold_value_progress),
    commissionProgress: numberValue(row.commissionProgress ?? row.commission_progress),
    activityProgress: numberValue(row.activityProgress ?? row.activity_progress),
  }
}

function toOption(row: Record<string, unknown>) {
  return { id: String(row.id ?? ''), label: String(row.label ?? '') }
}

function arrayValue(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value) ? (value as Record<string, unknown>[]) : []
}

function objectValue(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as Record<string, unknown>) : {}
}

function numberValue(value: unknown): number {
  const number = Number(value ?? 0)
  return Number.isFinite(number) ? number : 0
}
