import { describe, expect, it } from 'vitest'
import { seedUnits } from '../data/seed'
import {
  archiveUnitWorkflow,
  createUnitWorkflow,
  createUserWorkflow,
  deleteManagedUserWorkflow,
  deleteSalesRepresentativeWorkflow,
  deleteUnitAdminNoteWorkflow,
  saveUnitAdminNoteWorkflow,
  signInWorkflow,
  updateSettingsWorkflow,
  updateUnitStatusWorkflow,
  updateUnitWorkflow,
} from './workflows'
import type { AppDataState, LeadraUnit, LeadraUser, UnitEditInput } from './types'

const admin: LeadraUser = {
  id: 'admin-1',
  fullName: 'Admin User',
  email: 'admin@leadra.test',
  role: 'admin',
  jobTitle: 'Admin',
  phoneNumber: '+201000000001',
  teamId: 'team-a',
  branchId: 'branch-a',
  status: 'active',
}

const sales: LeadraUser = {
  id: 'sales-1',
  fullName: 'Sales User',
  email: 'sales@leadra.test',
  role: 'sales',
  jobTitle: 'Sales',
  phoneNumber: '+201000000002',
  teamId: 'team-a',
  branchId: 'branch-a',
  status: 'active',
}

const manager: LeadraUser = {
  id: 'manager-1',
  fullName: 'Manager User',
  email: 'manager@leadra.test',
  role: 'manager',
  jobTitle: 'Manager',
  phoneNumber: '+201000000004',
  teamId: 'team-a',
  branchId: 'branch-a',
  status: 'active',
}

function state(): AppDataState {
  return {
    users: [admin, sales],
    units: seedUnits,
    branches: [{ id: 'branch-a', name: 'Branch A' }],
    teams: [{ id: 'team-a', name: 'Team A', branchId: 'branch-a' }],
    notifications: [],
    auditLogs: [],
    analyticsEvents: [],
    analyticsTargets: [],
    settings: {
      companyName: 'Leadra',
      commissionPercentage: 1.5,
      footerText: 'Generated by Leadra',
      contactDetails: '0100 000 0000',
      logoPath: '',
      pdfLayout: 'classic',
      mediaLimitMb: 40,
      paymentMethods: ['cash', 'installment'],
    },
  }
}

function editInput(unit: LeadraUnit, overrides: Partial<UnitEditInput> = {}): UnitEditInput {
  return {
    developerId: unit.developerId,
    developerName: unit.developerName,
    projectId: unit.projectId,
    projectName: unit.projectName,
    destinationId: unit.destinationId,
    destinationName: unit.destinationName,
    unitType: unit.unitType,
    floor: unit.floor,
    bua: unit.bua,
    roofGardenArea: unit.roofGardenArea,
    gardenArea: unit.gardenArea,
    terraceArea: unit.terraceArea,
    viewId: unit.viewId,
    viewName: unit.viewName,
    bedrooms: unit.bedrooms,
    bathrooms: unit.bathrooms,
    elevator: unit.elevator,
    landArea: unit.landArea,
    furnished: unit.furnished,
    finish: unit.finish,
    deliveryExpectancy: unit.deliveryExpectancy,
    originalOwnerName: unit.originalOwnerName ?? '',
    countryCode: unit.countryCode ?? '+20',
    originalOwnerPhone: unit.originalOwnerPhone ?? '',
    salesNotes: unit.salesNotes,
    totalAmount: unit.totalAmount,
    commissionPercentage: unit.commissionPercentage,
    ...overrides,
  }
}

describe('Leadra product workflows', () => {
  it('blocks inactive users from signing in', () => {
    const inactive = { ...sales, id: 'inactive-1', email: 'inactive@leadra.test', status: 'inactive' as const }
    const result = signInWorkflow({ ...state(), users: [admin, inactive] }, 'inactive@leadra.test')

    expect(result.ok).toBe(false)
    expect(result.error).toBe('Inactive users cannot log in.')
  })

  it('allows only admin/sub-admin to create users and preserves audit history', () => {
    const result = createUserWorkflow(state(), admin, {
      fullName: 'New Manager',
      email: 'manager@leadra.test',
      password: 'Leadra8!',
      role: 'manager',
      jobTitle: 'Manager',
      phoneNumber: '+201000000003',
      teamId: 'team-a',
      branchId: 'branch-a',
      status: 'active',
    })

    expect(result.ok).toBe(true)
    expect(result.state.users).toHaveLength(3)
    expect(result.state.auditLogs.at(0)?.actionType).toBe('User created')
  })

  it('deactivates a sales representative only after reassigning their units to another active sales rep', () => {
    const replacement: LeadraUser = {
      ...sales,
      id: 'sales-2',
      fullName: 'Replacement Sales',
      email: 'replacement@leadra.test',
    }

    const result = deleteSalesRepresentativeWorkflow(
      { ...state(), users: [admin, sales, replacement] },
      admin,
      sales.id,
      replacement.id,
    )

    expect(result.ok).toBe(true)
    expect(result.state.users.find((item) => item.id === sales.id)).toMatchObject({
      status: 'inactive',
      deletedAt: expect.any(String),
    })
    expect(result.state.units.filter((unit) => unit.createdBy === sales.id)).toHaveLength(0)
    expect(result.state.units.filter((unit) => unit.createdBy === replacement.id).length).toBeGreaterThan(0)
    expect(result.state.units).toHaveLength(state().units.length)
    expect(result.state.auditLogs.at(0)).toMatchObject({
      actionType: 'Sales representative deactivated after reassignment',
      relatedUnitCode: sales.id,
    })
  })

  it('deactivates and hides a manager without reassigning units', () => {
    const result = deleteManagedUserWorkflow({ ...state(), users: [admin, sales, manager] }, admin, manager.id)

    expect(result.ok).toBe(true)
    expect(result.state.users.find((item) => item.id === manager.id)).toMatchObject({
      status: 'inactive',
      deletedAt: expect.any(String),
    })
    expect(result.state.units).toEqual(state().units)
    expect(result.state.auditLogs.at(0)).toMatchObject({
      actionType: 'User deactivated',
      relatedUnitCode: manager.id,
    })
  })

  it('creates a unit with normalized owner phone, notifications, audit log, and calculated values', () => {
    const result = createUnitWorkflow(state(), sales, {
      developerId: 'dev-palm',
      developerName: 'Palm Hills',
      projectId: 'project-zed',
      projectName: 'ZED East',
      destinationId: 'dest-new-cairo',
      destinationName: 'New Cairo',
      unitType: 'Apartment',
      floor: '1st',
      bua: 155,
      viewId: 'view-garden',
      viewName: 'Garden',
      bedrooms: 3,
      bathrooms: 2,
      elevator: true,
      finish: 'Fully Finished',
      furnished: false,
      paymentMethod: 'installment',
      totalAmount: 6_000_000,
      downPayment: 1_200_000,
      installmentType: 'annual',
      installmentYears: 4,
      deliveryExpectancy: { mode: 'year', year: 2029 },
      originalOwnerName: 'Unique Owner',
      countryCode: '+20',
      originalOwnerPhone: '010 3333 4444',
      salesNotes: 'Fresh resale lead.',
      media: [],
    })

    expect(result.ok).toBe(true)
    expect(result.state.units[0].normalizedOwnerPhone).toBe('+201033334444')
    expect(result.state.units[0].unitCode).toBe('ZE3BR')
    expect(result.state.units[0].remainingPayment).toBe(4_800_000)
    expect(result.state.units[0].installmentAmount).toBe(1_200_000)
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Unit created')
    expect(result.state.notifications.at(0)?.title).toBe('New unit uploaded')
    expect(result.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'unit_created',
      actorId: sales.id,
      actorRole: 'sales',
      unitId: result.state.units[0].id,
      projectId: 'project-zed',
      amountValue: 6_000_000,
      commissionValue: 90_000,
    })
    expect(JSON.stringify(result.state.analyticsEvents.at(0))).not.toMatch(/Unique Owner|3333|ownerPhone/i)
  })

  it('rejects same-project duplicate owner phone and records the attempt', () => {
    const result = createUnitWorkflow(state(), sales, {
      developerId: 'dev-palm',
      developerName: 'Palm Hills',
      projectId: 'project-new-cairo',
      projectName: 'New Cairo Estates',
      destinationId: 'dest-new-cairo',
      destinationName: 'New Cairo',
      unitType: 'Apartment',
      floor: '1st',
      bua: 155,
      viewId: 'view-garden',
      viewName: 'Garden',
      bedrooms: 3,
      bathrooms: 2,
      elevator: true,
      finish: 'Fully Finished',
      furnished: false,
      paymentMethod: 'cash',
      totalAmount: 6_000_000,
      deliveryExpectancy: { mode: 'year', year: 2029 },
      originalOwnerName: 'Duplicate Owner',
      countryCode: '+971',
      originalOwnerPhone: '+971 50 123 4567',
      salesNotes: 'Duplicate attempt.',
      media: [],
    })

    expect(result.ok).toBe(false)
    expect(result.error).toContain('Duplicate owner phone blocked')
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Duplicate owner phone attempt inside same project')
    expect(result.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'duplicate_phone_blocked',
      actorId: sales.id,
      projectId: 'project-new-cairo',
    })
  })

  it('rejects owner phone values that do not match the selected country format', () => {
    const result = createUnitWorkflow(state(), sales, {
      developerId: 'dev-palm',
      developerName: 'Palm Hills',
      projectId: 'project-zed',
      projectName: 'ZED East',
      destinationId: 'dest-new-cairo',
      destinationName: 'New Cairo',
      unitType: 'Apartment',
      floor: '1st',
      bua: 155,
      viewId: 'view-garden',
      viewName: 'Garden',
      bedrooms: 3,
      bathrooms: 2,
      elevator: true,
      finish: 'Fully Finished',
      furnished: false,
      paymentMethod: 'cash',
      totalAmount: 6_000_000,
      deliveryExpectancy: { mode: 'year', year: 2029 },
      originalOwnerName: 'Invalid Owner',
      countryCode: '+20',
      originalOwnerPhone: '12345',
      salesNotes: 'Invalid local phone.',
      media: [],
    })

    expect(result.ok).toBe(false)
    expect(result.error).toContain('Owner phone must match Egypt +20')
    expect(result.errorKey).toBe('error.invalidOwnerPhoneForCountry')
  })

  it('updates allowed unit fields and preserves remaining value when total value changes', () => {
    const unit = seedUnits[0]
    const result = updateUnitWorkflow(state(), sales, unit.id, editInput(unit, {
      bua: 180,
      totalAmount: 5_500_000,
      originalOwnerName: 'Blocked Sales Owner Edit',
      originalOwnerPhone: '0501234568',
      salesNotes: 'Updated from edit mode.',
    }))

    expect(result.ok).toBe(true)
    const updated = result.state.units.find((item) => item.id === unit.id)
    expect(updated).toMatchObject({
      bua: 180,
      totalAmount: 5_500_000,
      remainingPayment: unit.remainingPayment,
      originalOwnerName: unit.originalOwnerName,
      originalOwnerPhone: unit.originalOwnerPhone,
      salesNotes: 'Updated from edit mode.',
    })
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Total Value / pricing updated')
    expect(result.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'price_updated',
      unitId: unit.id,
      amountValue: 5_500_000,
    })
  })

  it('blocks manager edits outside team scope and pricing edits inside team scope', () => {
    const otherTeamUnit = seedUnits[1]
    const outsideTeam = updateUnitWorkflow(state(), manager, otherTeamUnit.id, editInput(otherTeamUnit, { bua: otherTeamUnit.bua + 10 }))
    expect(outsideTeam.ok).toBe(false)
    expect(outsideTeam.error).toContain('edit this unit')

    const teamUnit = seedUnits[0]
    const insideTeam = updateUnitWorkflow(state(), { ...manager, teamId: teamUnit.teamId }, teamUnit.id, editInput(teamUnit, {
      bua: teamUnit.bua + 10,
      totalAmount: teamUnit.totalAmount + 500_000,
    }))
    expect(insideTeam.ok).toBe(true)
    const updated = insideTeam.state.units.find((item) => item.id === teamUnit.id)
    expect(updated?.bua).toBe(teamUnit.bua + 10)
    expect(updated?.totalAmount).toBe(teamUnit.totalAmount)
  })

  it('lets admins edit owner fields with validation and duplicate-phone protection', () => {
    const unit = seedUnits[0]
    const changed = updateUnitWorkflow(state(), admin, unit.id, editInput(unit, {
      originalOwnerName: 'Updated Owner',
      countryCode: '+20',
      originalOwnerPhone: '010 3333 4444',
    }))

    expect(changed.ok).toBe(true)
    expect(changed.state.units.find((item) => item.id === unit.id)).toMatchObject({
      originalOwnerName: 'Updated Owner',
      originalOwnerPhone: '01033334444',
      normalizedOwnerPhone: '+201033334444',
    })

    const invalid = updateUnitWorkflow(state(), admin, unit.id, editInput(unit, {
      countryCode: '+20',
      originalOwnerPhone: '12345',
    }))
    expect(invalid.ok).toBe(false)
    expect(invalid.error).toContain('Owner phone must match')

    const duplicateUnit = { ...seedUnits[1], id: 200, projectId: unit.projectId, projectName: unit.projectName }
    const duplicate = updateUnitWorkflow(
      { ...state(), units: [unit, duplicateUnit] },
      admin,
      duplicateUnit.id,
      editInput(duplicateUnit, {
        countryCode: unit.countryCode ?? '+971',
        originalOwnerPhone: unit.originalOwnerPhone ?? '',
      }),
    )
    expect(duplicate.ok).toBe(false)
    expect(duplicate.error).toContain('Duplicate owner phone blocked')
  })

  it('archives and changes status only when the actor has permission', () => {
    const sold = updateUnitStatusWorkflow(state(), sales, 105, 'sold')
    expect(sold.ok).toBe(true)
    expect(sold.state.auditLogs.at(0)?.actionType).toBe('Unit marked Sold')
    expect(sold.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'status_changed',
      unitStatusBefore: 'available',
      unitStatusAfter: 'sold',
      amountValue: 5_000_000,
      commissionValue: 75_000,
    })

    const archived = archiveUnitWorkflow(sold.state, admin, 105)
    expect(archived.ok).toBe(true)
    expect(archived.state.units.find((unit) => unit.id === 105)?.archived).toBe(true)
    expect(archived.state.analyticsEvents.at(0)?.eventType).toBe('unit_archived')

    const managerArchive = archiveUnitWorkflow(sold.state, manager, 105)
    expect(managerArchive.ok).toBe(false)
    expect(managerArchive.errorKey).toBe('error.archiveNotAllowed')
    expect(managerArchive.state.units.find((unit) => unit.id === 105)?.archived).toBe(false)
  })

  it('lets authorized roles save, replace, and delete the single shared admin note', () => {
    const created = saveUnitAdminNoteWorkflow(state(), admin, 106, 'Need legal review before relisting.')
    expect(created.ok).toBe(true)
    expect(created.state.units.find((unit) => unit.id === 106)?.adminManagerNotes).toHaveLength(1)
    expect(created.state.auditLogs.at(0)?.actionType).toBe('Admin/manager note added')
    expect(created.state.analyticsEvents.at(0)?.eventType).toBe('note_added')

    const updated = saveUnitAdminNoteWorkflow(created.state, admin, 106, 'Legal review completed. Ready to relist.')
    expect(updated.ok).toBe(true)
    expect(updated.state.units.find((unit) => unit.id === 106)?.adminManagerNotes[0]?.content).toBe('Legal review completed. Ready to relist.')
    expect(updated.state.auditLogs.at(0)?.actionType).toBe('Admin/manager note updated')
    expect(updated.state.analyticsEvents.at(0)?.eventType).toBe('note_updated')

    const deleted = deleteUnitAdminNoteWorkflow(updated.state, admin, 106)
    expect(deleted.ok).toBe(true)
    expect(deleted.state.units.find((unit) => unit.id === 106)?.adminManagerNotes).toHaveLength(0)
    expect(deleted.state.auditLogs.at(0)?.actionType).toBe('Admin/manager note deleted')
    expect(deleted.state.analyticsEvents.at(0)?.eventType).toBe('note_deleted')
  })

  it('can clear a unit back to available and blocks sales users from managing admin notes', () => {
    const available = updateUnitStatusWorkflow(state(), sales, 106, 'available')
    expect(available.ok).toBe(true)
    expect(available.state.units.find((unit) => unit.id === 106)?.status).toBe('available')
    expect(available.state.auditLogs.at(0)?.actionType).toBe('Unit marked Available')

    const denied = saveUnitAdminNoteWorkflow(state(), sales, 105, 'Should not be allowed.')
    expect(denied.ok).toBe(false)
    expect(denied.error).toContain('Only Admin, Sub Admin, and Manager')
  })

  it('limits settings changes to admin and sub-admin roles', () => {
    expect(updateSettingsWorkflow(state(), sales, { commissionPercentage: 2 }).ok).toBe(false)

    const result = updateSettingsWorkflow(state(), admin, { commissionPercentage: 2 })
    expect(result.ok).toBe(true)
    expect(result.state.settings.commissionPercentage).toBe(2)
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Settings updated')
    expect(result.state.analyticsEvents.at(0)?.eventType).toBe('settings_updated')
  })
})
