import { describe, expect, it } from 'vitest'
import { seedUnits } from '../data/seed'
import {
  archiveUnitWorkflow,
  createUnitWorkflow,
  createUserWorkflow,
  signInWorkflow,
  updateSettingsWorkflow,
  updateUnitStatusWorkflow,
} from './workflows'
import type { AppDataState, LeadraUser } from './types'

const admin: LeadraUser = {
  id: 'admin-1',
  fullName: 'Admin User',
  email: 'admin@leadra.test',
  role: 'admin',
  jobTitle: 'Admin',
  phoneNumber: '+201000000001',
  teamId: 'team-a',
  branchId: 'branch-a',
  status: 'active',
}

const sales: LeadraUser = {
  id: 'sales-1',
  fullName: 'Sales User',
  email: 'sales@leadra.test',
  role: 'sales',
  jobTitle: 'Sales',
  phoneNumber: '+201000000002',
  teamId: 'team-a',
  branchId: 'branch-a',
  status: 'active',
}

function state(): AppDataState {
  return {
    users: [admin, sales],
    units: seedUnits,
    notifications: [],
    auditLogs: [],
    analyticsEvents: [],
    analyticsTargets: [],
    settings: {
      companyName: 'Leadra',
      commissionPercentage: 1.5,
      footerText: 'Generated by Leadra',
      contactDetails: '0100 000 0000',
      mediaLimitMb: 40,
      paymentMethods: ['cash', 'installment'],
    },
  }
}

describe('Leadra product workflows', () => {
  it('blocks inactive users from signing in', () => {
    const inactive = { ...sales, id: 'inactive-1', email: 'inactive@leadra.test', status: 'inactive' as const }
    const result = signInWorkflow({ ...state(), users: [admin, inactive] }, 'inactive@leadra.test')

    expect(result.ok).toBe(false)
    expect(result.error).toBe('Inactive users cannot log in.')
  })

  it('allows only admin/sub-admin to create users and preserves audit history', () => {
    const result = createUserWorkflow(state(), admin, {
      fullName: 'New Manager',
      email: 'manager@leadra.test',
      role: 'manager',
      jobTitle: 'Manager',
      phoneNumber: '+201000000003',
      teamId: 'team-a',
      branchId: 'branch-a',
      status: 'active',
    })

    expect(result.ok).toBe(true)
    expect(result.state.users).toHaveLength(3)
    expect(result.state.auditLogs.at(0)?.actionType).toBe('User created')
  })

  it('creates a unit with normalized owner phone, notifications, audit log, and calculated values', () => {
    const result = createUnitWorkflow(state(), sales, {
      developerId: 'dev-palm',
      developerName: 'Palm Hills',
      projectId: 'project-zed',
      projectName: 'ZED East',
      destinationId: 'dest-new-cairo',
      destinationName: 'New Cairo',
      unitType: 'Apartment',
      floor: '1st',
      bua: 155,
      viewId: 'view-garden',
      viewName: 'Garden',
      bedrooms: 3,
      bathrooms: 2,
      elevator: true,
      finish: 'Fully Finished',
      furnished: false,
      paymentMethod: 'installment',
      totalAmount: 6_000_000,
      downPayment: 1_200_000,
      installmentType: 'annual',
      installmentYears: 4,
      deliveryExpectancy: { mode: 'year', year: 2029 },
      originalOwnerName: 'Unique Owner',
      countryCode: '+20',
      originalOwnerPhone: '010 3333 4444',
      salesNotes: 'Fresh resale lead.',
      media: [],
    })

    expect(result.ok).toBe(true)
    expect(result.state.units[0].normalizedOwnerPhone).toBe('+201033334444')
    expect(result.state.units[0].remainingPayment).toBe(4_800_000)
    expect(result.state.units[0].installmentAmount).toBe(1_200_000)
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Unit created')
    expect(result.state.notifications.at(0)?.title).toBe('New unit uploaded')
    expect(result.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'unit_created',
      actorId: sales.id,
      actorRole: 'sales',
      unitId: result.state.units[0].id,
      projectId: 'project-zed',
      amountValue: 6_000_000,
      commissionValue: 90_000,
    })
    expect(JSON.stringify(result.state.analyticsEvents.at(0))).not.toMatch(/Unique Owner|3333|ownerPhone/i)
  })

  it('rejects same-project duplicate owner phone and records the attempt', () => {
    const result = createUnitWorkflow(state(), sales, {
      developerId: 'dev-palm',
      developerName: 'Palm Hills',
      projectId: 'project-new-cairo',
      projectName: 'New Cairo Estates',
      destinationId: 'dest-new-cairo',
      destinationName: 'New Cairo',
      unitType: 'Apartment',
      floor: '1st',
      bua: 155,
      viewId: 'view-garden',
      viewName: 'Garden',
      bedrooms: 3,
      bathrooms: 2,
      elevator: true,
      finish: 'Fully Finished',
      furnished: false,
      paymentMethod: 'cash',
      totalAmount: 6_000_000,
      deliveryExpectancy: { mode: 'year', year: 2029 },
      originalOwnerName: 'Duplicate Owner',
      countryCode: '+971',
      originalOwnerPhone: '+971 50 123 4567',
      salesNotes: 'Duplicate attempt.',
      media: [],
    })

    expect(result.ok).toBe(false)
    expect(result.error).toContain('Duplicate owner phone blocked')
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Duplicate owner phone attempt inside same project')
    expect(result.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'duplicate_phone_blocked',
      actorId: sales.id,
      projectId: 'project-new-cairo',
    })
  })

  it('archives and changes status only when the actor has permission', () => {
    const sold = updateUnitStatusWorkflow(state(), sales, 105, 'sold')
    expect(sold.ok).toBe(true)
    expect(sold.state.auditLogs.at(0)?.actionType).toBe('Unit marked Sold')
    expect(sold.state.analyticsEvents.at(0)).toMatchObject({
      eventType: 'status_changed',
      unitStatusBefore: 'available',
      unitStatusAfter: 'sold',
      amountValue: 5_000_000,
      commissionValue: 75_000,
    })

    const archived = archiveUnitWorkflow(sold.state, admin, 105)
    expect(archived.ok).toBe(true)
    expect(archived.state.units.find((unit) => unit.id === 105)?.archived).toBe(true)
    expect(archived.state.analyticsEvents.at(0)?.eventType).toBe('unit_archived')
  })

  it('limits settings changes to admin and sub-admin roles', () => {
    expect(updateSettingsWorkflow(state(), sales, { commissionPercentage: 2 }).ok).toBe(false)

    const result = updateSettingsWorkflow(state(), admin, { commissionPercentage: 2 })
    expect(result.ok).toBe(true)
    expect(result.state.settings.commissionPercentage).toBe(2)
    expect(result.state.auditLogs.at(0)?.actionType).toBe('Settings updated')
    expect(result.state.analyticsEvents.at(0)?.eventType).toBe('settings_updated')
  })
})
