create extension if not exists "pgcrypto";

create type public.user_role as enum ('admin', 'sub_admin', 'manager', 'sales');
create type public.account_status as enum ('active', 'inactive');
create type public.unit_status as enum ('available', 'hold', 'sold');
create type public.payment_method as enum ('cash', 'installment');
create type public.installment_type as enum ('quarterly', 'semi_annual', 'annual', 'custom');
create type public.lookup_kind as enum ('developer', 'project', 'destination', 'view', 'unit_type', 'finish');
create type public.media_type as enum ('image', 'pdf', 'video');
create type public.notification_channel as enum ('in_app', 'email');
create type public.analytics_event_type as enum (
  'unit_created',
  'unit_updated',
  'status_changed',
  'unit_archived',
  'media_uploaded',
  'note_added',
  'pdf_generated',
  'pdf_shared_or_downloaded',
  'duplicate_phone_blocked',
  'price_updated',
  'payment_updated',
  'installment_updated',
  'user_login',
  'inactive_user_detected',
  'settings_updated'
);
create type public.analytics_target_scope as enum ('company', 'team', 'user');
create type public.analytics_target_period as enum ('monthly', 'quarterly');

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  branch_id uuid references public.branches(id),
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete restrict,
  full_name text not null,
  email text not null unique,
  role public.user_role not null default 'sales',
  job_title text not null,
  phone_number text not null,
  team_id uuid references public.teams(id),
  branch_id uuid references public.branches(id),
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table public.lookup_values (
  id uuid primary key default gen_random_uuid(),
  kind public.lookup_kind not null,
  label text not null,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  unique (kind, label)
);

create table public.app_settings (
  id boolean primary key default true,
  commission_percentage numeric(5,2) not null default 1.50,
  company_name text not null default 'Leadra',
  footer_text text not null default 'Generated by Leadra resale system',
  contact_details text,
  logo_path text,
  media_limit_mb integer not null default 40,
  updated_at timestamptz not null default now(),
  constraint app_settings_singleton check (id)
);

insert into public.app_settings (id) values (true) on conflict (id) do nothing;

create table public.units (
  id bigserial primary key,
  unit_code text unique,
  developer_id uuid not null references public.lookup_values(id),
  project_id uuid not null references public.lookup_values(id),
  destination_id uuid not null references public.lookup_values(id),
  unit_type text not null,
  floor text not null,
  bua numeric(12,2) not null check (bua > 0),
  roof_garden_area numeric(12,2),
  view_id uuid references public.lookup_values(id),
  bedrooms integer not null check (bedrooms between 1 and 10),
  bathrooms integer not null check (bathrooms between 1 and 10),
  elevator boolean not null default false,
  land_area numeric(12,2),
  furnished boolean not null default false,
  finish text not null,
  payment_method public.payment_method not null,
  total_amount numeric(14,2) not null check (total_amount >= 0),
  down_payment numeric(14,2),
  remaining_payment numeric(14,2),
  commission_percentage numeric(5,2) not null default 1.50,
  commission_amount numeric(14,2) generated always as (round(total_amount * commission_percentage / 100, 2)) stored,
  installment_type public.installment_type,
  installment_years integer,
  installment_amount numeric(14,2),
  delivery_month integer check (delivery_month between 1 and 12),
  delivery_year integer not null check (delivery_year >= 2026),
  original_owner_name text not null,
  country_code text not null,
  original_owner_phone text not null,
  normalized_owner_phone text not null,
  sales_notes text default '',
  status public.unit_status not null default 'available',
  archived boolean not null default false,
  created_by uuid not null references public.profiles(id),
  team_id uuid references public.teams(id),
  branch_id uuid references public.branches(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint one_payment_method check (
    (payment_method = 'cash' and down_payment is null and remaining_payment is null and installment_type is null and installment_years is null and installment_amount is null)
    or
    (payment_method = 'installment' and down_payment is not null and remaining_payment is not null and installment_type is not null)
  )
);

create unique index units_project_owner_phone_unique
  on public.units(project_id, normalized_owner_phone)
  where archived = false;

create table public.unit_media (
  id uuid primary key default gen_random_uuid(),
  unit_id bigint not null references public.units(id) on delete cascade,
  type public.media_type not null,
  storage_path text not null,
  file_name text not null,
  size_bytes bigint not null check (size_bytes > 0),
  include_in_pdf boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.unit_notes (
  id uuid primary key default gen_random_uuid(),
  unit_id bigint not null references public.units(id) on delete cascade,
  content text not null,
  created_by uuid not null references public.profiles(id),
  created_by_role public.user_role not null,
  is_admin_manager_note boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles(id),
  actor_role public.user_role not null,
  action_type text not null,
  related_unit_id bigint references public.units(id),
  previous_value jsonb,
  new_value jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id),
  audience_role public.user_role,
  title text not null,
  body text not null,
  channel public.notification_channel not null default 'in_app',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.notification_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  in_app_enabled boolean not null default true,
  email_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  event_type public.analytics_event_type not null,
  actor_id uuid references public.profiles(id),
  actor_role public.user_role not null,
  team_id uuid references public.teams(id),
  branch_id uuid references public.branches(id),
  unit_id bigint references public.units(id),
  project_id uuid references public.lookup_values(id),
  developer_id uuid references public.lookup_values(id),
  destination_id uuid references public.lookup_values(id),
  unit_status_before public.unit_status,
  unit_status_after public.unit_status,
  amount_value numeric(14,2),
  commission_value numeric(14,2),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint analytics_events_metadata_no_owner_data check (
    metadata::text !~* '(owner|phone|normalized_owner|original_owner)'
  )
);

create index analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index analytics_events_scope_idx on public.analytics_events(team_id, event_type, created_at desc);
create index analytics_events_unit_idx on public.analytics_events(unit_id);

create table public.analytics_targets (
  id uuid primary key default gen_random_uuid(),
  scope_type public.analytics_target_scope not null,
  scope_id uuid,
  period public.analytics_target_period not null,
  target_units_created integer not null default 0 check (target_units_created >= 0),
  target_units_sold integer not null default 0 check (target_units_sold >= 0),
  target_sold_value numeric(14,2) not null default 0 check (target_sold_value >= 0),
  target_commission numeric(14,2) not null default 0 check (target_commission >= 0),
  target_activity_events integer not null default 0 check (target_activity_events >= 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint analytics_targets_scope_required check (
    (scope_type = 'company' and scope_id is null)
    or (scope_type in ('team', 'user') and scope_id is not null)
  ),
  constraint analytics_targets_valid_window check (ends_at > starts_at)
);

create index analytics_targets_scope_idx on public.analytics_targets(scope_type, scope_id, starts_at, ends_at);

create or replace function public.current_profile()
returns public.profiles
language sql
stable
security definer
set search_path = public
as $$
  select * from public.profiles where id = auth.uid();
$$;

create or replace function public.current_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() and status = 'active';
$$;

create or replace function public.current_team_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select team_id from public.profiles where id = auth.uid() and status = 'active';
$$;

create or replace function public.normalize_owner_phone(local_phone text, selected_country_code text)
returns text
language plpgsql
immutable
as $$
declare
  cleaned text := regexp_replace(coalesce(local_phone, ''), '[\s\-\(\)]', '', 'g');
  country_digits text := regexp_replace(coalesce(selected_country_code, ''), '\D', '', 'g');
  local_digits text;
begin
  if cleaned like '00%' then
    cleaned := '+' || substring(cleaned from 3);
  end if;

  if cleaned like '+%' then
    return '+' || regexp_replace(substring(cleaned from 2), '\D', '', 'g');
  end if;

  local_digits := regexp_replace(cleaned, '\D', '', 'g');
  if starts_with(local_digits, country_digits) then
    return '+' || local_digits;
  end if;

  return '+' || country_digits || regexp_replace(local_digits, '^0+', '');
end;
$$;

create or replace function public.prepare_unit_calculations()
returns trigger
language plpgsql
as $$
declare
  destination_label text;
  payments_per_year integer;
begin
  new.normalized_owner_phone := public.normalize_owner_phone(new.original_owner_phone, new.country_code);
  new.remaining_payment := case when new.payment_method = 'installment' then new.total_amount - coalesce(new.down_payment, 0) else null end;

  if new.payment_method = 'cash' then
    new.down_payment := null;
    new.remaining_payment := null;
    new.installment_type := null;
    new.installment_years := null;
    new.installment_amount := null;
  elsif new.installment_type = 'custom' then
    new.installment_amount := null;
  else
    payments_per_year := case new.installment_type when 'quarterly' then 4 when 'semi_annual' then 2 when 'annual' then 1 else null end;
    new.installment_amount := round(new.remaining_payment / nullif((coalesce(new.installment_years, 0) * payments_per_year), 0), 2);
  end if;

  if new.unit_code is null then
    select label into destination_label from public.lookup_values where id = new.destination_id;
    new.unit_code := upper(left(regexp_replace(coalesce(destination_label, 'NA'), '[^A-Za-z]', '', 'g'), 2)) || new.id || 'BR' || new.bedrooms || 'Ba' || new.bathrooms;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

create trigger units_prepare_calculations
before insert or update on public.units
for each row execute function public.prepare_unit_calculations();

alter table public.branches enable row level security;
alter table public.teams enable row level security;
alter table public.profiles enable row level security;
alter table public.lookup_values enable row level security;
alter table public.app_settings enable row level security;
alter table public.units enable row level security;
alter table public.unit_media enable row level security;
alter table public.unit_notes enable row level security;
alter table public.audit_logs enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_targets enable row level security;

create policy "active users read branches" on public.branches for select using (public.current_role() is not null);
create policy "active users read teams" on public.teams for select using (public.current_role() is not null);
create policy "admins manage branches" on public.branches for all using (public.current_role() in ('admin', 'sub_admin')) with check (public.current_role() in ('admin', 'sub_admin'));
create policy "admins manage teams" on public.teams for all using (public.current_role() in ('admin', 'sub_admin')) with check (public.current_role() in ('admin', 'sub_admin'));

create policy "users read own profile and admins read all" on public.profiles
for select using (id = auth.uid() or public.current_role() in ('admin', 'sub_admin'));
create policy "admins manage profiles" on public.profiles
for all using (public.current_role() in ('admin', 'sub_admin')) with check (public.current_role() in ('admin', 'sub_admin'));

create policy "active users read lookup values" on public.lookup_values for select using (public.current_role() is not null);
create policy "admins manage lookup values" on public.lookup_values
for all using (public.current_role() in ('admin', 'sub_admin')) with check (public.current_role() in ('admin', 'sub_admin'));

create policy "admins read settings" on public.app_settings for select using (public.current_role() is not null);
create policy "admins update settings" on public.app_settings
for update using (public.current_role() in ('admin', 'sub_admin')) with check (public.current_role() in ('admin', 'sub_admin'));

create policy "unit visibility by role" on public.units
for select using (
  public.current_role() in ('admin', 'sub_admin')
  or (public.current_role() = 'manager' and team_id = public.current_team_id())
  or (public.current_role() = 'sales' and archived = false)
);

create policy "any active user creates units" on public.units
for insert with check (public.current_role() is not null and created_by = auth.uid());

create policy "unit edit by role" on public.units
for update using (
  public.current_role() in ('admin', 'sub_admin')
  or (public.current_role() = 'manager' and team_id = public.current_team_id())
  or (public.current_role() = 'sales' and created_by = auth.uid() and archived = false)
) with check (
  public.current_role() in ('admin', 'sub_admin')
  or (public.current_role() = 'manager' and team_id = public.current_team_id())
  or (public.current_role() = 'sales' and created_by = auth.uid() and archived = false)
);

create policy "media follows unit visibility" on public.unit_media
for select using (exists (select 1 from public.units u where u.id = unit_id));
create policy "active users add media to own visible units" on public.unit_media
for insert with check (public.current_role() is not null);

create policy "notes follow unit visibility" on public.unit_notes
for select using (exists (select 1 from public.units u where u.id = unit_id));
create policy "sales note or manager note insert" on public.unit_notes
for insert with check (
  public.current_role() is not null
  and created_by = auth.uid()
  and (
    is_admin_manager_note = false
    or public.current_role() in ('admin', 'sub_admin', 'manager')
  )
);

create policy "admins read audit logs" on public.audit_logs for select using (public.current_role() in ('admin', 'sub_admin'));
create policy "active users insert audit logs" on public.audit_logs for insert with check (public.current_role() is not null);

create policy "notification visibility" on public.notifications
for select using (user_id = auth.uid() or audience_role = public.current_role());
create policy "active users insert notifications" on public.notifications for insert with check (public.current_role() is not null);

create policy "users manage own notification preferences" on public.notification_preferences
for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "analytics events visibility by role" on public.analytics_events
for select using (
  public.current_role() in ('admin', 'sub_admin')
  or (public.current_role() = 'manager' and team_id = public.current_team_id())
);
create policy "active users insert analytics events" on public.analytics_events
for insert with check (public.current_role() is not null and (actor_id is null or actor_id = auth.uid()));

create policy "analytics targets visibility by role" on public.analytics_targets
for select using (
  public.current_role() in ('admin', 'sub_admin')
  or (public.current_role() = 'manager' and scope_type = 'team' and scope_id = public.current_team_id())
);
create policy "admins manage analytics targets" on public.analytics_targets
for all using (public.current_role() in ('admin', 'sub_admin')) with check (public.current_role() in ('admin', 'sub_admin'));

create or replace function public.analytics_overview_summary()
returns table (
  total_active_units bigint,
  available_units bigint,
  hold_units bigint,
  sold_units bigint,
  sold_value numeric,
  projected_commission numeric,
  active_users bigint,
  duplicate_attempts bigint,
  pdf_exports bigint,
  inactive_users bigint,
  archived_units bigint
)
language sql
stable
as $$
  select
    count(*) filter (where u.archived = false) as total_active_units,
    count(*) filter (where u.archived = false and u.status = 'available') as available_units,
    count(*) filter (where u.archived = false and u.status = 'hold') as hold_units,
    count(*) filter (where u.archived = false and u.status = 'sold') as sold_units,
    coalesce(sum(u.total_amount) filter (where u.status = 'sold'), 0) as sold_value,
    coalesce(sum(u.commission_amount) filter (where u.archived = false), 0) as projected_commission,
    (select count(*) from public.profiles p where p.status = 'active' and (public.current_role() in ('admin', 'sub_admin') or p.team_id = public.current_team_id())) as active_users,
    (select count(*) from public.analytics_events e where e.event_type = 'duplicate_phone_blocked') as duplicate_attempts,
    (select count(*) from public.analytics_events e where e.event_type in ('pdf_generated', 'pdf_shared_or_downloaded')) as pdf_exports,
    (select count(*) from public.profiles p where p.status = 'inactive' and (public.current_role() in ('admin', 'sub_admin') or p.team_id = public.current_team_id())) as inactive_users,
    count(*) filter (where u.archived = true) as archived_units
  from public.units u
  where public.current_role() in ('admin', 'sub_admin', 'manager');
$$;

create or replace function public.analytics_sales_performance()
returns table (
  user_id uuid,
  user_name text,
  team_id uuid,
  units_created bigint,
  units_sold bigint,
  sold_value numeric,
  commission_contribution numeric,
  activity_count bigint,
  last_activity_at timestamptz
)
language sql
stable
as $$
  select
    p.id as user_id,
    p.full_name as user_name,
    p.team_id,
    count(distinct u.id) as units_created,
    count(distinct u.id) filter (where u.status = 'sold') as units_sold,
    coalesce(sum(u.total_amount) filter (where u.status = 'sold'), 0) as sold_value,
    coalesce(sum(u.commission_amount) filter (where u.status = 'sold'), 0) as commission_contribution,
    count(e.id) as activity_count,
    max(e.created_at) as last_activity_at
  from public.profiles p
  left join public.units u on u.created_by = p.id
  left join public.analytics_events e on e.actor_id = p.id
  where p.role = 'sales' and public.current_role() in ('admin', 'sub_admin', 'manager')
  group by p.id, p.full_name, p.team_id
  having count(distinct u.id) > 0 or count(e.id) > 0
  order by activity_count desc, sold_value desc;
$$;

create or replace function public.analytics_inventory_health()
returns table (
  project_id uuid,
  total_units bigint,
  available_units bigint,
  hold_units bigint,
  sold_units bigint,
  average_price numeric,
  media_completeness numeric
)
language sql
stable
as $$
  select
    u.project_id,
    count(*) as total_units,
    count(*) filter (where u.status = 'available') as available_units,
    count(*) filter (where u.status = 'hold') as hold_units,
    count(*) filter (where u.status = 'sold') as sold_units,
    round(avg(u.total_amount), 2) as average_price,
    round((count(distinct m.unit_id)::numeric / nullif(count(distinct u.id), 0)) * 100, 2) as media_completeness
  from public.units u
  left join public.unit_media m on m.unit_id = u.id
  where u.archived = false and public.current_role() in ('admin', 'sub_admin', 'manager')
  group by u.project_id
  order by total_units desc;
$$;

create or replace function public.analytics_activity_timeline(days_back integer default 90)
returns table (
  activity_date date,
  units_created bigint,
  status_changes bigint,
  sold_value numeric,
  pdf_exports bigint,
  activity_count bigint
)
language sql
stable
as $$
  select
    e.created_at::date as activity_date,
    count(*) filter (where e.event_type = 'unit_created') as units_created,
    count(*) filter (where e.event_type = 'status_changed') as status_changes,
    coalesce(sum(e.amount_value) filter (where e.event_type = 'status_changed' and e.unit_status_after = 'sold'), 0) as sold_value,
    count(*) filter (where e.event_type in ('pdf_generated', 'pdf_shared_or_downloaded')) as pdf_exports,
    count(*) as activity_count
  from public.analytics_events e
  where e.created_at >= now() - make_interval(days => greatest(days_back, 1))
    and public.current_role() in ('admin', 'sub_admin', 'manager')
  group by e.created_at::date
  order by activity_date;
$$;

create or replace function public.analytics_targets_progress()
returns table (
  target_id uuid,
  scope_type public.analytics_target_scope,
  scope_id uuid,
  period public.analytics_target_period,
  target_activity_events integer,
  actual_activity_events bigint
)
language sql
stable
as $$
  select
    t.id,
    t.scope_type,
    t.scope_id,
    t.period,
    t.target_activity_events,
    count(e.id) as actual_activity_events
  from public.analytics_targets t
  left join public.analytics_events e
    on e.created_at between t.starts_at and t.ends_at
    and (
      t.scope_type = 'company'
      or (t.scope_type = 'team' and e.team_id = t.scope_id)
      or (t.scope_type = 'user' and e.actor_id = t.scope_id)
    )
  where public.current_role() in ('admin', 'sub_admin', 'manager')
  group by t.id, t.scope_type, t.scope_id, t.period, t.target_activity_events
  order by t.starts_at desc;
$$;

insert into storage.buckets (id, name, public)
values ('unit-media', 'unit-media', false), ('company-assets', 'company-assets', false)
on conflict (id) do nothing;
